// AMSE IT Solutions GmbH - Scenarios
import { Scenario } from '@kritis/shared';

export const amseScenarios: Scenario[] = [
  {
    id: 'AMSE-SC-001',
    title: 'Die Firewall-Regel die nicht existiert',
    category: 'vendor_management',
    difficulty: 2,
    flavorText: 'Du richtest einen neuen Dienst ein der Port 8443 von intern nach extern braucht. Du fragst Marco bei AMSE, ob er die Firewall-Regel anlegen kann. Marco antwortet nach 2 Stunden: \'Ist erledigt, Regel ist drin.\' Du testest — Port ist immer noch zu.',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Marco zurückschreiben: \'Funktioniert nicht, Port ist noch zu\'',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Marco: \'Das kann nicht sein, ich hab die Regel angelegt. Vielleicht liegt es an eurem internen Routing?\' Du verbringst 45 Minuten mit internem Troubleshooting. Alles ok auf deiner Seite. Du schreibst Marco nochmal. Er meldet sich morgen.',
        scoreChange: 0,
        reputationChange: 0,
        lesson: 'Bei externen Dienstleistern reicht \'funktioniert nicht\' oft nicht. Du brauchst Beweise.',
      },
      {
        id: 'B',
        text: 'Selbst in die Sophos-Konsole einloggen und die Regel prüfen',
        outcome: 'PERFECT',
        consequence: 'Du loggst dich in Sophos Central ein und siehst: Keine Regel für Port 8443. Nichts. Marco hat es entweder vergessen oder in der falschen Firewall-Policy angelegt (er verwaltet 12 Kunden). Du machst einen Screenshot, schickst ihn Marco: \'Hier ist der aktuelle Regelstand — ich sehe keine 8443-Regel.\' Marco: \'...ah, Moment. Ich glaube ich war in der falschen Konsole.\'',
        scoreChange: 100,
        reputationChange: 15,
        lesson: 'IMMER selbst verifizieren statt dem Dienstleister blind vertrauen. Eigener Lesezugriff auf Firewall/Sophos Central ist Pflicht. \'Trust but verify\' — besonders bei Dienstleistern die viele Kunden betreuen.',
      },
      {
        id: 'C',
        text: 'Auf Marcos Wort vertrauen und intern weiter suchen',
        outcome: 'FAIL',
        consequence: 'Du verbringst 3 Stunden mit Routing-Checks, DNS-Diagnose, und Windows-Firewall-Prüfung. Alles ok. Am Ende loggst du dich in die Sophos ein: Keine Regel. 3 Stunden verloren weil du dem Dienstleister geglaubt hast.',
        scoreChange: -75,
        reputationChange: -5,
        lesson: 'Wenn der Dienstleister sagt \'bei uns ist alles ok\', ist das eine Behauptung, kein Beweis. Prüfe immer selbst bevor du intern suchst.',
      },
      {
        id: 'D',
        text: 'Die Regel selbst anlegen und Marco informieren',
        outcome: 'SUCCESS',
        consequence: 'Du legst die Regel selbst an. Funktioniert sofort. Du informierst Marco: \'Hab die Regel selbst angelegt, hier die Doku.\' Marco ist leicht pikiert, aber es spart allen Zeit. Allerdings: Wenn du regelmäßig Marcos Arbeit machst, warum bezahlt ihr AMSE?',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Selbst machen ist manchmal effizienter, aber es verschleiert das eigentliche Problem: Der Dienstleister liefert nicht. Dokumentiere solche Vorfälle für Vertragsgespräche.',
      },
    ],
    realWorldReference: 'Managed Security Service Provider (MSSPs) betreuen oft 20+ Kunden gleichzeitig. Verwechslungen und Copy-Paste-Fehler sind leider verbreitet.',
    bsiReference: 'BSI IT-Grundschutz: OPS.2.1 Outsourcing',
    involvedNpcs: ['AMSE-MARCO'],
    tags: ['firewall', 'sophos', 'vendor', 'verify'],
  },
  {
    id: 'AMSE-SC-002',
    title: 'VPN funktioniert nicht — \'Liegt nicht an der Firewall\'',
    category: 'vendor_management',
    difficulty: 3,
    flavorText: '5 Mitarbeiter im Homeoffice melden: VPN trennt sich alle 30 Minuten und reconnected. Du fragst Marco. Antwort: \'VPN-Konfiguration ist korrekt, das liegt am Provider der Mitarbeiter oder an deren Heimnetzwerken.\'',
    urgency: 'high',
    choices: [
      {
        id: 'A',
        text: 'Marcos Aussage akzeptieren und die 5 Mitarbeiter bitten, ihren Heim-Router zu prüfen',
        outcome: 'FAIL',
        consequence: 'Die Mitarbeiter rufen ihre Provider an, die sagen \'bei uns ist alles ok\'. 5 verschiedene Provider, 5 verschiedene Router, alle das gleiche Problem. Nach 2 Tagen Hin-und-Her loggst du dich in die Sophos ein: VPN-Timeout steht auf 1800 Sekunden (30 Minuten). Das ist der Standard-Wert den AMSE nie angepasst hat.',
        scoreChange: -100,
        reputationChange: -10,
        lesson: 'Wenn alle das gleiche Problem haben, liegt es nicht am Einzelnen. Das ist ein Server-/Config-Problem. \'Alle 5 Provider gleichzeitig kaputt\' ist extrem unwahrscheinlich.',
      },
      {
        id: 'B',
        text: 'In den Sophos-Logs die VPN-Disconnects analysieren',
        outcome: 'PERFECT',
        consequence: 'Die Logs zeigen: \'Phase 2 lifetime expired, renegotiating.\' Alle 1800 Sekunden. Der Session-Timeout ist zu kurz konfiguriert — AMSE hat den Default nie angepasst. Du zeigst Marco die Logs mit Timestamps: exakt alle 30 Minuten, bei ALLEN Usern. Marco: \'...ich passe das an.\' Timeout auf 8 Stunden gesetzt. Problem gelöst.',
        scoreChange: 150,
        reputationChange: 20,
        lesson: 'Logs sind Beweise. Wenn du dem Dienstleister mit konkreten Logeinträgen und Timestamps kommst, kann er nicht mehr sagen \'liegt nicht an uns\'. IPsec Phase 2 Lifetime und Dead Peer Detection sind häufige VPN-Problemquellen.',
      },
      {
        id: 'C',
        text: 'Marco bitten, sich per Fernwartung bei einem betroffenen Mitarbeiter aufzuschalten',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Marco schaltet sich auf, wartet 30 Minuten, sieht den Disconnect live. \'Hm, das ist komisch.\' Er prüft JETZT erst die Firewall-Config und findet den Timeout. Problem gelöst — aber es hat einen Tag gedauert, weil er erst nicht hinschauen wollte.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Den Dienstleister dazu bringen, das Problem live zu sehen, kann helfen — aber es ist zeitaufwändig. Eigene Log-Analyse ist schneller und liefert härtere Beweise.',
      },
    ],
    realWorldReference: 'IPsec-VPN-Timeouts sind eine der häufigsten Ursachen für VPN-Disconnects. Default-Werte passen selten zur produktiven Nutzung.',
    bsiReference: 'BSI IT-Grundschutz: NET.3.3 VPN',
    involvedNpcs: ['AMSE-MARCO'],
    tags: ['vpn', 'ipsec', 'logs', 'troubleshooting'],
  },
  {
    id: 'AMSE-SC-003',
    title: 'Freitag 16:47 — \'Wir spielen kurz ein Update ein\'',
    category: 'vendor_management',
    difficulty: 4,
    flavorText: 'Freitag, 16:47 Uhr. Du willst gerade gehen. Mail von Marco: \'Hi, wir spielen heute Abend das Sophos-Firmware-Update ein. Sollte ca. 15 Min Downtime geben. Gruß, Marco.\' Keine Abstimmung, kein Change-Request, kein Wartungsfenster vereinbart.',
    urgency: 'high',
    choices: [
      {
        id: 'A',
        text: 'Sofort Marco anrufen: \'STOPP — kein Update ohne Change-Request und genehmigtes Wartungsfenster\'',
        outcome: 'PERFECT',
        consequence: 'Du erreichst Marco gerade noch. Er ist genervt: \'Ist doch nur ein Minor-Update.\' Du erklärst: KRITIS-Betreiber brauchen dokumentierte Change-Prozesse. Ihr vereinbart ein Wartungsfenster für nächsten Dienstag 22 Uhr, mit Rollback-Plan und deiner Bereitschaft. Marco grummelt, macht es aber.',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'Änderungen an KRITIS-Infrastruktur brauchen IMMER: Change-Request, Genehmigung, geplantes Wartungsfenster, Rollback-Plan, und jemanden der erreichbar ist wenn es schiefgeht. Freitag 17 Uhr ist der schlechteste Zeitpunkt für Änderungen.',
      },
      {
        id: 'B',
        text: 'OK sagen aber dabei bleiben und das Update überwachen',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Du bleibst bis 19 Uhr. Das Update läuft durch — mit 45 Minuten Downtime statt 15. Dabei fällt auch die VoIP-Telefonie aus, was Marco \'vergessen\' hatte zu erwähnen. Kein Schaden, aber auch kein dokumentierter Change-Prozess.',
        scoreChange: 25,
        reputationChange: 5,
        lesson: 'Dabei bleiben ist besser als blind vertrauen, aber ohne Change-Prozess gibt es keine Dokumentation, kein Rollback-Konzept, und keine Verantwortlichkeiten. Das ist bei KRITIS nicht akzeptabel.',
      },
      {
        id: 'C',
        text: 'Die Mail erst Montag lesen — ist ja schon Feierabend',
        outcome: 'CRITICAL_FAIL',
        consequence: 'Marco spielt das Update Freitagabend ein. Es gibt ein Problem mit der VPN-Konfiguration — die wird beim Update zurückgesetzt. Samstag morgen: kein VPN, keine Bereitschaft erreichbar. Die Leitstelle, die am Wochenende per VPN arbeitet, ist offline. Müllabfuhr am Samstag fährt ohne Disposition.',
        scoreChange: -300,
        reputationChange: -25,
        lesson: 'E-Mails von Dienstleistern am Freitagnachmittag mit dem Wort \'Update\' SOFORT lesen. Die Kombination \'Freitag + Update + keine Abstimmung\' ist der #1 Ausfallgrund weltweit.',
        triggersEvent: 'WEEKEND_OUTAGE',
      },
      {
        id: 'D',
        text: 'Antworten: \'Bitte erst nach Rücksprache. Und: Warum Freitag Abend?\'',
        outcome: 'SUCCESS',
        consequence: 'Marco: \'Weil ich heute Abend sowieso noch bei einem anderen Kunden Updates mache und es dann gleich mitmachen wollte.\' BINGO — er wollte dein Update zwischen zwei andere Kunden quetschen. Du bestehst auf separatem, geplantem Termin.',
        scoreChange: 100,
        reputationChange: 15,
        lesson: 'Dienstleister konsolidieren gerne Wartungsarbeiten über mehrere Kunden. Das spart IHNEN Zeit, erhöht aber DEIN Risiko (Zeitdruck, geteilte Aufmerksamkeit, keine individuelle Vorbereitung).',
      },
    ],
    realWorldReference: 'Freitag-Deployments sind laut DevOps-Statistiken 3x häufiger fehlerursächlich als Dienstag-Deployments. \'Deploy Friday\' ist ein Anti-Pattern.',
    bsiReference: 'BSI IT-Grundschutz: OPS.1.1.3 Patch- und Änderungsmanagement',
    involvedNpcs: ['AMSE-MARCO'],
    tags: ['change-management', 'update', 'kritis', 'friday'],
  },
  {
    id: 'AMSE-SC-004',
    title: 'Die kopierte Firewall-Regel vom anderen Kunden',
    category: 'security_incident',
    difficulty: 4,
    flavorText: 'Du prüfst routinemäßig die Firewall-Regeln in Sophos und findest eine Regel die dir nicht bekannt vorkommt: \'Allow ANY → ANY von IP 10.42.0.0/16\'. Euer Netzwerk ist 10.10.0.0/16. Das 10.42er Netz gehört euch nicht. Die Regel wurde vor 3 Monaten von \'admin_amse\' angelegt.',
    urgency: 'high',
    choices: [
      {
        id: 'A',
        text: 'Marco sofort konfrontieren: \'Was ist diese Regel? Wem gehört 10.42.0.0/16?\'',
        outcome: 'PERFECT',
        consequence: 'Marco wird blass. 10.42.0.0/16 ist das Netzwerk eines anderen AMSE-Kunden. Marco hat beim Anlegen eurer Regeln eine Vorlage vom anderen Kunden kopiert und vergessen, die IP anzupassen. Die Regel erlaubt theoretisch Traffic von einem FREMDEN Netzwerk durch eure Firewall. Marco löscht die Regel sofort und entschuldigt sich.',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'Dienstleister die Templates zwischen Kunden kopieren, hinterlassen Artefakte. Regelmäßige Firewall-Rule-Reviews sind Pflicht — besonders bei extern verwalteten Firewalls. Jede Regel muss einem dokumentierten Zweck zugeordnet sein.',
        followupEvent: 'AMSE_CONFIG_AUDIT',
      },
      {
        id: 'B',
        text: 'Die Regel selbst löschen und Marco informieren',
        outcome: 'SUCCESS',
        consequence: 'Du löschst die Regel, dokumentierst den Fund, und informierst Marco. Er reagiert defensiv: \'Die Regel war sicher nicht aktiv.\' (War sie doch.) Du forderst einen kompletten Regelaudit. Marco verspricht ihn \'nächste Woche\'. Du bekommst ihn nach 3 Wochen.',
        scoreChange: 150,
        reputationChange: 15,
        lesson: 'Sicherheitsrisiken sofort beheben, dann klären. Aber: Den Dienstleister in die Aufklärung einbeziehen, damit er den Fehler versteht und nicht wiederholt.',
      },
      {
        id: 'C',
        text: 'Ignorieren — die Regel tut wahrscheinlich nichts weil das 10.42er Netz nicht erreichbar ist',
        outcome: 'CRITICAL_FAIL',
        consequence: '3 Monate später: AMSE richtet ein Site-to-Site-VPN für einen neuen Kunden ein — mit dem 10.42er Netz. Durch die vergessene Regel kann der neue Kunde plötzlich auf euer internes Netz zugreifen. Datenleck über Kreuz zwischen zwei KRITIS-Betreibern.',
        scoreChange: -400,
        reputationChange: -30,
        lesson: 'Unbekannte Firewall-Regeln sind NIEMALS harmlos. Heute vielleicht wirkungslos, morgen ein Einfallstor. \'Defense in Depth\' bedeutet auch: Aufräumen was nicht gebraucht wird.',
        triggersEvent: 'CROSS_CUSTOMER_BREACH',
      },
    ],
    realWorldReference: 'MSSP-Konfigurationsfehler durch Copy-Paste zwischen Kunden sind ein reales und häufiges Problem. Der Kaseya-Angriff 2021 nutzte die Vertrauensstellung zwischen MSP und Kunden aus.',
    bsiReference: 'BSI IT-Grundschutz: NET.3.2 Firewall, OPS.2.1 Outsourcing',
    involvedNpcs: ['AMSE-MARCO'],
    tags: ['security', 'firewall', 'cross-customer', 'audit'],
  },
  {
    id: 'AMSE-SC-005',
    title: 'SLA-Realitätscheck — Der \'kritische\' Ausfall',
    category: 'vendor_management',
    difficulty: 3,
    flavorText: 'Montagmorgen, 8:02 Uhr. Die Internet-Verbindung am Hauptstandort ist komplett weg. Alle 120 Mitarbeiter betroffen. Du rufst AMSE an. Die Ansage: \'Sie sind Anrufer Nummer 4. Bitte bleiben Sie in der Leitung.\' Nach 25 Minuten geht Marco ran: \'Ach, bei euch auch? Ich hab hier gerade 3 andere Kunden mit dem gleichen Problem.\'',
    urgency: 'critical',
    choices: [
      {
        id: 'A',
        text: 'Marco drängen: \'Wir sind KRITIS, wir haben Priorität laut SLA!\'',
        outcome: 'SUCCESS',
        consequence: 'Marco priorisiert dich — nach 2 Stunden. Die Ursache: AMSE hat am Wochenende ein DNS-Update auf ihrer Seite ausgerollt, das bei 4 Kunden gleichzeitig den externen DNS-Resolver kaputtgemacht hat. Dein Internet war nie \'weg\' — nur die DNS-Auflösung funktionierte nicht.',
        scoreChange: 50,
        reputationChange: 10,
        lesson: 'SLA-Eskalation funktioniert, aber ist reaktiv. Besser: Eigene DNS-Resolver konfigurieren (z.B. 1.1.1.1 als Fallback) um nicht von der DNS-Konfiguration des Dienstleisters abhängig zu sein.',
      },
      {
        id: 'B',
        text: 'Selbst diagnostizieren: Ist es wirklich die Leitung oder nur DNS/Routing?',
        outcome: 'PERFECT',
        consequence: 'Du pingst die Gateway-IP: geht. Du pingst 8.8.8.8: geht. Du pingst google.de: geht nicht. DNS! Du setzt den DNS-Resolver auf den Clients temporär auf 1.1.1.1 und 9.9.9.9. Internet läuft sofort wieder. Dann rufst du Marco an: \'Euer DNS-Server ist kaputt. Wir laufen auf Fallback. Bitte fixen.\' Marco: \'...oh.\'',
        scoreChange: 250,
        reputationChange: 25,
        lesson: 'Basis-Netzwerkdiagnose (Ping IP vs. Ping Hostname) unterscheidet sofort zwischen Leitungsproblem und DNS-Problem. Eigene DNS-Fallback-Konfiguration macht dich unabhängiger vom Dienstleister.',
      },
      {
        id: 'C',
        text: 'Warten bis AMSE das Problem löst — dafür bezahlen wir sie ja',
        outcome: 'FAIL',
        consequence: 'AMSE braucht 4 Stunden um den DNS-Server zu fixen (sie hatten 4 Kunden gleichzeitig und mussten priorisieren). 4 Stunden kein Internet für 120 Mitarbeiter. Produktivitätsverlust: geschätzt 9.600€. Für ein DNS-Problem, das du in 5 Minuten hättest umgehen können.',
        scoreChange: -200,
        reputationChange: -15,
        lesson: '100% Abhängigkeit vom Dienstleister ist ein Risiko. Basis-Problemlösung muss intern möglich sein. Wer bei jedem DNS-Problem 4 Stunden warten muss, hat ein Architekturproblem.',
      },
      {
        id: 'D',
        text: 'Stefan (AMSE-GF) anrufen und eskalieren',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Stefan: \'Ich nehme das persönlich in die Hand!\' Er legt auf und ruft Marco an: \'Der KRITIS-Kunde hat Prio!\' Marco arbeitet jetzt unter Druck, macht einen Tippfehler im DNS-Fix, und bringt auch den Mailserver durcheinander. Ausfall verlängert sich um 2 Stunden.',
        scoreChange: -50,
        reputationChange: 5,
        lesson: 'Eskalation an die Geschäftsführung des Dienstleisters erzeugt Druck, aber Druck verursacht Fehler. Besser: Eigene Diagnose stellt sicher, dass der Techniker das richtige Problem bearbeitet.',
      },
    ],
    realWorldReference: 'DNS ist die häufigste Ursache für \'Internet geht nicht\' — laut Cloudflare verursachen DNS-Probleme 30% aller Internet-Ausfälle.',
    bsiReference: 'BSI IT-Grundschutz: NET.1.2 Netzmanagement, APP.3.6 DNS-Server',
    involvedNpcs: ['AMSE-MARCO', 'AMSE-STEFAN'],
    tags: ['dns', 'outage', 'sla', 'troubleshooting'],
  },
  {
    id: 'AMSE-SC-006',
    title: 'Die Sophos-Lizenz ist abgelaufen',
    category: 'vendor_management',
    difficulty: 3,
    flavorText: 'Du bekommst eine Sophos-Warnmail: \'Ihre Lizenz für Web Protection läuft in 7 Tagen ab.\' Seltsam — AMSE sollte die Lizenzverlängerung organisiert haben. Du fragst Marco. Antwort nach 2 Tagen: \'Ups, das ist durchgerutscht. Ich kümmere mich.\'',
    urgency: 'high',
    choices: [
      {
        id: 'A',
        text: 'Marco vertrauen und warten',
        outcome: 'FAIL',
        consequence: 'Tag 7: Lizenz abgelaufen. Web Protection deaktiviert. Alle User können jetzt ungefiltert surfen. Malware-Sites, Phishing-Domains — alles offen. Marco: \'Die Bestellung ist raus, dauert leider 3-5 Werktage.\' 5 Tage ohne Web-Filter in einem KRITIS-Netz.',
        scoreChange: -300,
        reputationChange: -20,
        lesson: 'Lizenzverwaltung NIEMALS komplett dem Dienstleister überlassen. Eigene Erinnerungen 90/60/30/14/7 Tage vor Ablauf einrichten. Sophos Central zeigt Lizenzstatus — regelmäßig prüfen.',
      },
      {
        id: 'B',
        text: 'Selbst in Sophos Central den Lizenzstatus prüfen und parallel direkt bei Sophos die Verlängerung anstoßen',
        outcome: 'PERFECT',
        consequence: 'Du prüfst: Lizenz läuft wirklich in 7 Tagen aus. Du kontaktierst parallel den Sophos-Vertrieb für ein Direktangebot. AMSE bekommt die Verlängerung am letzten Tag noch hin, aber du hattest einen Plan B. Außerdem richtest du eigene Lizenz-Alerts in Sophos Central ein.',
        scoreChange: 200,
        reputationChange: 15,
        lesson: 'Kritische Lizenzen müssen intern überwacht werden, auch wenn der Dienstleister zuständig ist. Sophos Central hat eigene Lizenz-Notifications — aktivieren und nicht nur den Dienstleister-Alerts vertrauen.',
      },
      {
        id: 'C',
        text: 'Eskalation an Stefan (AMSE-GF) mit Verweis auf SLA-Verletzung',
        outcome: 'SUCCESS',
        consequence: 'Stefan verspricht \'sofortige Lösung\'. Die Bestellung kommt rechtzeitig — 2 Tage vor Ablauf. Aber nur weil Stefan persönlich den Sophos-Partner angerufen hat. Langfristig ändert sich bei AMSEs Lizenzverwaltung nichts.',
        scoreChange: 75,
        reputationChange: 10,
        lesson: 'GF-Eskalation funktioniert kurzfristig, ist aber keine Prozessverbesserung. Wenn Lizenzen nur durch Eskalation rechtzeitig verlängert werden, braucht man einen besseren Prozess — oder einen besseren Dienstleister.',
      },
    ],
    realWorldReference: 'Abgelaufene Security-Lizenzen sind ein häufiger und vermeidbarer Sicherheitsvorfall. Laut Gartner haben 25% der Unternehmen mindestens eine abgelaufene Security-Lizenz im Netz.',
    bsiReference: 'BSI IT-Grundschutz: OPS.1.1.5 Protokollierung, OPS.2.1 Outsourcing',
    involvedNpcs: ['AMSE-MARCO', 'AMSE-STEFAN'],
    tags: ['license', 'sophos', 'security', 'deadline'],
  },
  {
    id: 'AMSE-SC-007',
    title: 'Die Dokumentation die es nicht gibt',
    category: 'vendor_management',
    difficulty: 3,
    flavorText: 'Du erstellst die Netzwerkdokumentation für den NIS2-Audit. Du fragst Marco nach der Firewall-Dokumentation: Regelwerk-Übersicht, Netzplan, VPN-Topologie, NAT-Regeln. Marco: \'Klar, schick ich dir morgen.\' 1 Woche später: nichts. Du fragst nach. Marco: \'Sorry, bin gerade im Stress. Kommt diese Woche.\' 2 Wochen später: immer noch nichts.',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Dokumentation selbst aus Sophos Central exportieren und erstellen',
        outcome: 'SUCCESS',
        consequence: 'Du exportierst Firewall-Regeln, VPN-Konfiguration und NAT-Tabellen selbst aus Sophos Central. Es dauert einen ganzen Tag, aber du hast jetzt eine vollständige Dokumentation. Die du von nun an SELBST pflegst.',
        scoreChange: 150,
        reputationChange: 10,
        lesson: 'Wenn der Dienstleister nicht dokumentiert, musst du es selbst tun. Eigene Dokumentation ist sowieso besser, weil du die Änderungen nachvollziehen kannst. Firewall-Rule-Exports regelmäßig als Baseline sichern.',
      },
      {
        id: 'B',
        text: 'Schriftlich mit Fristsetzung anfordern: \'Dokumentation bis Freitag, ansonsten SLA-Eskalation\'',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Marco liefert Freitagabend ein 4-seitiges PDF mit groben Überschriften und ohne Details. \'Detaillierte Doku folgt.\' Folgt natürlich nie. Aber du hast jetzt einen schriftlichen Nachweis, dass du die Doku angefordert hast — wichtig für den Audit.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Fristen und schriftliche Kommunikation sind bei Dienstleistern essentiell. Mündliche Zusagen sind wertlos. Aber: Realistische Erwartung haben — eine gute Firewall-Doku schreibt man nicht in 2 Tagen.',
      },
      {
        id: 'C',
        text: 'Im Vertrag nachschauen ob Dokumentation Teil der Leistung ist',
        outcome: 'PERFECT',
        consequence: 'Du liest den Vertrag: §7 Absatz 3 — \'Auftragnehmer erstellt und pflegt eine vollständige Dokumentation aller Konfigurationen und übergibt diese quartalsmäßig.\' AMSE hat seit 5 Jahren keine Quartalsdokumentation geliefert. Du schreibst Stefan eine höfliche aber bestimmte Mail mit Vertragsreferenz. Die Dokumentation kommt in 10 Tagen. Vollständig.',
        scoreChange: 200,
        reputationChange: 25,
        lesson: 'IMMER den Vertrag kennen. Dokumentationspflichten stehen oft drin, werden aber nie eingefordert. Vertragsreferenz in Kommunikation mit Dienstleistern wirkt Wunder.',
      },
    ],
    realWorldReference: 'Fehlende Dokumentation durch externe Dienstleister ist eines der häufigsten Audit-Findings. Bei KRITIS-Audits kann fehlende Netzwerkdokumentation zum Nicht-Bestehen führen.',
    bsiReference: 'BSI IT-Grundschutz: OPS.2.1 Outsourcing, ORP.5 Compliance Management',
    involvedNpcs: ['AMSE-MARCO', 'AMSE-STEFAN'],
    tags: ['documentation', 'nis2', 'audit', 'contract'],
  },
  {
    id: 'AMSE-SC-008',
    title: 'AMSE-Techniker hat offene Session — seit 47 Tagen',
    category: 'security_incident',
    difficulty: 3,
    flavorText: 'Bei einer Routine-Prüfung in Sophos Central siehst du: \'Letzte Admin-Anmeldung: admin_amse — Aktiv seit 47 Tagen.\' Marco hat eine Management-Session offen gelassen. Seit 47 Tagen. Ohne Timeout. Von einer IP die du nicht kennst.',
    urgency: 'high',
    choices: [
      {
        id: 'A',
        text: 'Session sofort beenden und Marcos Zugangspasswort ändern',
        outcome: 'PERFECT',
        consequence: 'Du beendest die Session und änderst das Passwort. Dann rufst du Marco an: \'Ich hab deine offene Firewall-Session nach 47 Tagen geschlossen und das Passwort geändert. Wir richten jetzt MFA ein.\' Marco: \'Oh... äh... ja, sollten wir wahrscheinlich machen.\' Du richtest MFA für alle Admin-Accounts ein und setzt Session-Timeouts auf 4 Stunden.',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'Admin-Sessions ohne Timeout sind ein massives Sicherheitsrisiko. Wenn der Laptop des Technikers kompromittiert wird, hat der Angreifer Firewall-Admin-Zugang. MFA und Session-Timeouts sind Pflicht für alle Admin-Zugänge.',
      },
      {
        id: 'B',
        text: 'Marco informieren und ihn bitten, die Session zu schließen',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Marco: \'Ach stimmt, ich lass die manchmal offen damit ich schnell draufkomme wenn ihr anruft.\' Er schließt sie. Nächste Woche: wieder eine offene Session. Ohne MFA und Timeout-Policy ändert sich nichts.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Bitten hilft nicht nachhaltig. Technische Maßnahmen (Session-Timeout, MFA) sind die Lösung. Verlasse dich nie auf die Disziplin einzelner Personen.',
      },
      {
        id: 'C',
        text: 'Prüfen ob die unbekannte IP zu AMSE gehört oder ob der Account kompromittiert ist',
        outcome: 'PERFECT_ALTERNATIVE',
        consequence: 'Du machst einen Whois-Lookup: Die IP gehört zu einer Privatadresse — Marcos Homeoffice-DSL. OK, nicht kompromittiert. ABER: Marco administriert eure KRITIS-Firewall von seinem privaten Heimnetzwerk? Ohne VPN? Du eskalierst an Stefan: \'Euer Techniker administriert unsere KRITIS-Firewall aus einem privaten Netzwerk ohne VPN. Das ist eine NIS2-Verletzung.\'',
        scoreChange: 250,
        reputationChange: 25,
        lesson: 'KRITIS-Administration über private Netzwerke ohne VPN und MFA ist ein schwerer Compliance-Verstoß. Dienstleister müssen dieselben Sicherheitsstandards einhalten wie interne Admins. Das muss vertraglich geregelt sein.',
        triggersEvent: 'AMSE_SECURITY_AUDIT',
      },
    ],
    realWorldReference: 'Der SolarWinds-Angriff 2020 nutzte u.a. kompromittierte Dienstleister-Zugänge. MSSP-Accounts sind bevorzugte Ziele für Angreifer weil sie Zugang zu vielen Kunden bieten.',
    bsiReference: 'BSI IT-Grundschutz: OPS.2.1 Outsourcing, ORP.4 Identitäts- und Berechtigungsmanagement',
    involvedNpcs: ['AMSE-MARCO', 'AMSE-STEFAN'],
    tags: ['security', 'mfa', 'session', 'compliance'],
  },
];
