// Cloud365 GmbH - Microsoft Partner - Scenarios
import { Scenario } from '@kritis/shared';

export const cloud365Scenarios: Scenario[] = [
  {
    id: 'CLOUD365-SC-001',
    title: 'Die Lizenz die plötzlich teurer wurde',
    category: 'vendor_management',
    difficulty: 2,
    flavorText: 'Monatliche Azure-Rechnung kommt: €4.200 statt der üblichen €2.800. Du rufst Martin an. "Ah ja, Microsoft hat die Preise für die D-Series VMs angepasst. Stand doch in der E-Mail letzte Woche?" Du hast keine E-Mail bekommen.',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Die Rechnung akzeptieren — Microsoft-Preise kann man nicht verhandeln',
        outcome: 'FAIL',
        consequence: 'Die neuen Preise bleiben. €1.400/Monat mehr, €16.800/Jahr. Der Kämmerer fragt: "Warum wussten wir das nicht vorher?" Gute Frage — Cloud365 hätte warnen müssen.',
        scoreChange: -100,
        reputationChange: -10,
        lesson: 'Cloud-Kosten sind nicht fix. Microsoft ändert Preise regelmäßig. Eigenes Monitoring mit Azure Cost Management und Alerts bei Kostensprüngen sind Pflicht.',
      },
      {
        id: 'B',
        text: 'Azure Cost Management selbst einrichten und Budget-Alerts setzen',
        outcome: 'PERFECT',
        consequence: 'Du richtest Azure Cost Management mit Alerts bei 80%, 100% und 120% des Monatsbudgets ein. Du analysierst: Die D-Series VMs sind überdimensioniert. Du skalierst auf B-Series herunter: €1.600/Monat. Günstiger als vorher. Martin ist überrascht: "Oh, das hätte ich auch vorschlagen können."',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'Azure Cost Management ist kostenlos und mächtig. Eigenes Kosten-Monitoring macht dich unabhängig vom Partner. Regelmäßige Right-Sizing-Reviews sparen oft 30-50% der Cloud-Kosten.',
      },
      {
        id: 'C',
        text: 'Kevin beauftragen, die Kosten zu optimieren',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Kevin schaut drauf: "Ich kann Reserved Instances vorschlagen — 40% Rabatt bei 1-Jahr-Commitment." Gut, aber: Jetzt bist du 1 Jahr an diese VM-Größe gebunden. Flexibilität weg. Und Kevin hat 2 Stunden Beratung berechnet.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Reserved Instances sparen Geld, aber binden Flexibilität. Der Partner verdient an Beratung — eigenes Wissen über Azure-Kostenoptimierung ist wertvoller.',
      },
    ],
    realWorldReference: 'Microsoft passt Azure-Preise regelmäßig an. April 2024 gab es z.B. 15% Erhöhung für bestimmte VM-Typen. Ohne eigenes Monitoring erfährt man das erst auf der Rechnung.',
    bsiReference: 'BSI IT-Grundschutz: OPS.2.2 Cloud-Nutzung',
    involvedNpcs: ['CLOUD365-MARTIN'],
    tags: ['azure', 'costs', 'monitoring', 'budgeting'],
  },
  {
    id: 'CLOUD365-SC-002',
    title: 'Der Exchange-zu-M365-Migrationstag',
    category: 'troubleshooting',
    difficulty: 4,
    flavorText: 'Heute ist der große Tag: Exchange On-Prem wird zu Exchange Online migriert. Kevin versichert: "Alles vorbereitet, läuft automatisch, Benutzer merken nichts." 10:00 Uhr: Erste Beschwerde — "Mein Outlook funktioniert nicht mehr." 10:05 Uhr: 47 weitere Beschwerden.',
    urgency: 'critical',
    choices: [
      {
        id: 'A',
        text: 'Kevin sofort anrufen: "Stopp die Migration!"',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Kevin: "Stoppen geht nicht mehr, die Mailboxen sind halb migriert." Ihr arbeitet gemeinsam die nächsten 6 Stunden. Problem: Das Autodiscover war nicht richtig konfiguriert. Outlook findet die neuen Server nicht. Manuelle Profil-Neukonfiguration für 150 User. Migration abgeschlossen um 22 Uhr.',
        scoreChange: 25,
        reputationChange: 5,
        lesson: 'Migrationen haben einen "Point of no Return". Vorher testen, testen, testen. Autodiscover-Konfiguration ist der häufigste Exchange-Migrationsfehler.',
      },
      {
        id: 'B',
        text: 'Pilotgruppe checken: Wurde die wirklich erfolgreich migriert?',
        outcome: 'PERFECT',
        consequence: 'Du checkst die 10-User-Pilotgruppe: "Kevin, bei denen funktioniert Outlook auch nicht." Kevin: "...ähm." Es stellt sich heraus: Die Pilotmigration lief, aber Kevin hat nie getestet ob Outlook danach noch funktioniert. Ihr rollt auf den On-Prem-Exchange zurück, fixt das Autodiscover, macht einen echten Pilottest mit 5 Usern. Zweiter Anlauf am Samstag: läuft.',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'Pilotmigrationen müssen vollständig getestet werden, nicht nur "Migration erfolgreich". End-to-End-Test: Kann der User wirklich arbeiten? Outlook öffnen, Mail senden, Kalender prüfen.',
      },
      {
        id: 'C',
        text: 'Alle Mitarbeiter anweisen, Outlook zu schließen und Webmail zu nutzen',
        outcome: 'SUCCESS',
        consequence: 'Outlook Web Access funktioniert. Alle arbeiten im Browser während Kevin das Autodiscover fixt. Nicht ideal, aber arbeitsfähig. Um 16 Uhr funktioniert auch Outlook wieder. Der Tag ist gerettet — halbwegs.',
        scoreChange: 100,
        reputationChange: 10,
        lesson: 'Webmail ist ein valider Fallback während Client-Problemen. User können arbeiten während das Problem gefixt wird. Kommunikation und Workaround-Anweisungen sind bei Migrationen essenziell.',
      },
    ],
    realWorldReference: 'Exchange-zu-M365-Migrationen scheitern häufig an Autodiscover-Konfiguration. Microsoft empfiehlt Hybrid-Deployment mit Extended-Koexistenz, aber das ist aufwändig.',
    bsiReference: 'BSI IT-Grundschutz: OPS.1.1.3 Patch- und Änderungsmanagement',
    involvedNpcs: ['CLOUD365-KEVIN'],
    tags: ['exchange', 'migration', 'm365', 'email'],
  },
  {
    id: 'CLOUD365-SC-003',
    title: 'Microsoft Authenticator: "Wir ändern die Defaults"',
    category: 'security_incident',
    difficulty: 3,
    flavorText: 'Montagmorgen: 40 Mitarbeiter können sich nicht einloggen. Fehlermeldung: "MFA erforderlich." Problem: Die hatten nie MFA eingerichtet. Kevin: "Oh, Microsoft hat \'Security Defaults\' automatisch aktiviert. Das ist eigentlich gut für die Sicherheit..."',
    urgency: 'critical',
    choices: [
      {
        id: 'A',
        text: 'Security Defaults deaktivieren um den Betrieb wiederherzustellen',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Du deaktivierst Security Defaults im Azure AD. Alle können wieder arbeiten. Aber jetzt habt ihr KEIN MFA mehr. Kevin: "Wir sollten Conditional Access einrichten, das ist flexibler." Das hätte er vor der Microsoft-Änderung vorschlagen können.',
        scoreChange: 50,
        reputationChange: 0,
        lesson: 'Security Defaults sind Microsofts "Einsteiger-Sicherheit" — gut gemeint, aber unflexibel. Für KRITIS-Betreiber ist Conditional Access besser: Gleiche Sicherheit, mehr Kontrolle über Ausnahmen und Rollout.',
      },
      {
        id: 'B',
        text: 'Allen betroffenen Usern schnell MFA einrichten — heute noch',
        outcome: 'SUCCESS',
        consequence: 'Du und Kevin richtet für alle 40 User MFA ein — Microsoft Authenticator oder SMS. Dauert bis 14 Uhr, aber danach ist alles sicher UND funktional. Ein paar User sind genervt, aber das ist die Zukunft.',
        scoreChange: 150,
        reputationChange: 15,
        lesson: 'MFA-Rollout unter Druck ist chaotisch aber machbar. Besser: Geplanter MFA-Rollout mit Schulung und Vorlaufzeit. Aber lieber hektisch als gar nicht.',
      },
      {
        id: 'C',
        text: 'Microsoft-Änderungsankündigungen checken: Wusste Kevin davon?',
        outcome: 'PERFECT',
        consequence: 'Du checkst das Microsoft 365 Message Center: Die Änderung war 6 Wochen vorher angekündigt. Kevin: "Äh... ich check das nicht jeden Tag." Du richtest einen Flow ein der Message-Center-Posts automatisch als E-Mail an dich und Kevin schickt. Und ihr plant einen ordentlichen MFA-Rollout.',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'Das Microsoft 365 Message Center ist PFLICHTLEKTÜRE. Alle größeren Änderungen werden dort angekündigt. Automatische Alerts einrichten. Den Partner fragen: "Monitoren Sie das Message Center?" Wenn nein: Problem.',
        followupEvent: 'M365_MESSAGE_CENTER_SETUP',
      },
    ],
    realWorldReference: 'Microsoft aktiviert Security Defaults automatisch für Tenants ohne Conditional Access. Stand 2024 sind >50% aller M365-Tenants betroffen. Die Ankündigung kommt immer — aber wer liest schon das Message Center?',
    bsiReference: 'BSI IT-Grundschutz: ORP.4 Identitäts- und Berechtigungsmanagement',
    involvedNpcs: ['CLOUD365-KEVIN'],
    tags: ['mfa', 'security', 'azure-ad', 'defaults'],
  },
  {
    id: 'CLOUD365-SC-004',
    title: 'Der OneDrive-Sync der alles löscht',
    category: 'troubleshooting',
    difficulty: 3,
    flavorText: 'Ein Kollege meldet panisch: "Meine Dokumente sind weg! Alles!" Du checkst: Sein OneDrive-Ordner ist leer. Sein Desktop auch. Der OneDrive-Sync-Client zeigt: "Sync abgeschlossen. 0 Dateien." 4.000 Dateien sind verschwunden.',
    urgency: 'critical',
    choices: [
      {
        id: 'A',
        text: 'OneDrive-Papierkorb und Versionsverlauf prüfen',
        outcome: 'PERFECT',
        consequence: 'Du öffnest OneDrive im Browser, gehst auf "Papierkorb": Alle 4.000 Dateien sind da. Der User hat versehentlich den Sync-Ordner gelöscht, und OneDrive hat das synchronisiert. Du stellst alles wieder her. Dauert 20 Minuten. Kevin hätte das auch gewusst — aber der ist im Meeting.',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'OneDrive hat einen eigenen Papierkorb (93 Tage Aufbewahrung) und Versionsverlauf. Die meisten "gelöscht"-Paniken sind in 10 Minuten gelöst. Den Papierkorb im Browser zu kennen ist essenziell.',
      },
      {
        id: 'B',
        text: 'Kevin anrufen: "Kannst du das aus dem Backup wiederherstellen?"',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Kevin: "OneDrive HAT kein klassisches Backup... aber die Dateien sind wahrscheinlich im Papierkorb." Du findest sie dort. Aber: Du hast 2 Stunden gewartet während Kevin im Meeting war. Der User war panisch.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Sich auf den Partner verlassen kostet Zeit. Basis-OneDrive-Administration (Papierkorb, Sharing, Speicher) sollte intern bekannt sein. Der Partner ist für komplexe Probleme da, nicht für Papierkorb-Fragen.',
      },
      {
        id: 'C',
        text: 'Lokales Backup prüfen — haben wir eins?',
        outcome: 'FAIL',
        consequence: 'Du prüfst: Kein lokales Backup von OneDrive-Daten. Kevin hat damals gesagt: "Die Cloud ist das Backup!" Microsoft garantiert aber nur Verfügbarkeit, nicht Wiederherstellung bei Nutzerfehler. Glück gehabt, dass die Dateien im Papierkorb waren — das ist nicht garantiert.',
        scoreChange: -75,
        reputationChange: -5,
        lesson: 'Microsofts SLA garantiert Plattform-Verfügbarkeit, nicht Daten-Wiederherstellung bei Nutzerfehlern oder Ransomware. Ein Third-Party-Backup für M365 (Veeam, Acronis, etc.) ist bei KRITIS Pflicht.',
      },
    ],
    realWorldReference: 'Die Shared-Responsibility-Model-Lücke: Microsoft betreibt die Plattform, aber DU bist für deine Daten verantwortlich. Ransomware synchronisiert auch — und verschlüsselt den Papierkorb gleich mit.',
    bsiReference: 'BSI IT-Grundschutz: CON.3 Datensicherungskonzept, OPS.2.2 Cloud-Nutzung',
    involvedNpcs: ['CLOUD365-KEVIN'],
    tags: ['onedrive', 'backup', 'recovery', 'cloud'],
  },
  {
    id: 'CLOUD365-SC-005',
    title: 'Teams-Telefonie: "Das ist alles Cloud-native"',
    category: 'vendor_management',
    difficulty: 4,
    flavorText: 'Kevin präsentiert: "Teams-Telefonie ersetzt eure TK-Anlage! Alles in der Cloud, keine Hardware mehr, super Qualität!" Der GF ist begeistert. Du fragst: "Was passiert wenn das Internet ausfällt?" Kevin: "...äh..."',
    urgency: 'low',
    choices: [
      {
        id: 'A',
        text: 'Die kritischen Fragen stellen: Redundanz, Notruf, Fax, Türsprechanlage?',
        outcome: 'PERFECT',
        consequence: 'Du fragst systematisch ab: "Notruf-Standortübermittlung? Fax-Unterstützung? Analog-Schnittstellen für Türklingel und Aufzug? Fallback bei Internet-Ausfall?" Kevin kann 3 von 5 Fragen nicht beantworten. Der GF sagt: "Dann evaluieren wir das nochmal gründlicher."',
        scoreChange: 200,
        reputationChange: 25,
        lesson: 'Cloud-Telefonie hat Einschränkungen: Notruf braucht spezielle Konfiguration, Analoggeräte brauchen Adapter, bei Internet-Ausfall steht alles still. Für KRITIS ist ein LTE-Backup für Telefonie Pflicht.',
      },
      {
        id: 'B',
        text: 'Einen Pilottest vorschlagen: 10 User, 3 Monate',
        outcome: 'SUCCESS',
        consequence: 'Ihr startet einen Pilot. Nach 6 Wochen: Sprachqualität gut, aber das Fax für die Müllanmeldungen funktioniert nicht über Teams. Und beim Internet-Ausfall letzte Woche war auch Telefonie weg. Kevin: "Dafür gibt es Lösungen..." — die kosten extra.',
        scoreChange: 150,
        reputationChange: 15,
        lesson: 'Pilotprojekte decken Probleme auf bevor der ganze Betrieb umgestellt wird. 3 Monate sind realistisch um alle Edge Cases zu finden. Nie die ganze Telefonie auf einmal umstellen.',
      },
      {
        id: 'C',
        text: 'Kevin vertrauen und die Migration planen',
        outcome: 'FAIL',
        consequence: 'Migration auf Teams-Telefonie läuft. Woche 2: Die Leitstelle kann keine Bürger-Beschwerden mehr annehmen — Warteschleife funktioniert anders als bei der alten TK. Der Fax-zu-Mail-Gateway ist nicht DSGVO-konform. Das Aufzug-Notrufsystem geht nicht mehr. 3 Wochen Chaos.',
        scoreChange: -200,
        reputationChange: -25,
        lesson: 'Telefonie-Migration ist komplex und betrifft oft Systeme an die niemand denkt: Aufzugnotruf, Türsprechanlage, Alarm-Weiterleitung, Fax. Eine vollständige Anforderungsanalyse VORHER erspart Wochen Ärger.',
        triggersEvent: 'TELEPHONY_CHAOS',
      },
    ],
    realWorldReference: 'Teams-Telefonie ist ausgereift für Standard-Büro-Kommunikation. Aber Analog-Integration, Notruf, und Hochverfügbarkeit sind komplexe Themen die oft unterschätzt werden.',
    bsiReference: 'BSI IT-Grundschutz: NET.4.2 VoIP',
    involvedNpcs: ['CLOUD365-KEVIN', 'CLOUD365-MARTIN'],
    tags: ['teams', 'telephony', 'migration', 'requirements'],
  },
  {
    id: 'CLOUD365-SC-006',
    title: 'Copilot für Microsoft 365 — der KI-Assistent',
    category: 'compliance',
    difficulty: 3,
    flavorText: 'Martin ruft begeistert an: "Copilot ist jetzt für alle verfügbar! KI in Word, Excel, Teams — revolutionär!" Der Preis: €30/User/Monat extra. Und: "Das sieht alle eure Daten um zu lernen." Du zuckst zusammen.',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Datenschutz-Folgenabschätzung fordern: Was sieht Copilot?',
        outcome: 'PERFECT',
        consequence: 'Du forderst eine DSFA. Kevin liefert nach 2 Wochen: Copilot indexiert alle SharePoint-Dateien, E-Mails, Teams-Chats. Auch die Personaldaten. Auch die Gehaltslisten. Auch die Beschwerden über den GF. Du: "Das geht so nicht." Ihr implementiert Sensitivity Labels und Zugriffssteuerung BEVOR Copilot aktiv wird.',
        scoreChange: 250,
        reputationChange: 30,
        lesson: 'KI-Tools wie Copilot sehen ALLES worauf der User Zugriff hat — auch wenn er es nie öffnet. Berechtigungskonzept und Datenklassifizierung müssen VOR dem KI-Rollout stehen. Sonst findet jeder plötzlich sensible Daten.',
        followupEvent: 'DATA_CLASSIFICATION_PROJECT',
      },
      {
        id: 'B',
        text: 'Pilotgruppe mit IT-Team starten — wir verstehen erstmal die Technologie',
        outcome: 'SUCCESS',
        consequence: 'Du startest mit 5 IT-Usern. Nach 2 Wochen: "Copilot hat mir ein altes Protokoll aus 2019 gefunden in dem ich den Kämmerer kritisiert habe... das hatte ich total vergessen." Die Gefahr wird greifbar. Ihr überarbeitet das Berechtigungskonzept.',
        scoreChange: 150,
        reputationChange: 15,
        lesson: 'Pilotprojekte mit IT-Team zuerst — ihr versteht die Risiken bevor die Fachabteilung damit arbeitet. Und ihr entdeckt Datenleichen die durch KI plötzlich wieder auftauchen.',
      },
      {
        id: 'C',
        text: 'Für alle aktivieren — KI ist die Zukunft!',
        outcome: 'CRITICAL_FAIL',
        consequence: 'Woche 1: Ein Mitarbeiter fragt Copilot nach "Gehaltsstrukturen" und bekommt eine Zusammenfassung der Management-Gehälter. Woche 2: Der Betriebsrat fragt nach "Abmahnungen" und findet alle HR-Dokumente. Woche 3: Ein Journalist fragt einen Ex-Mitarbeiter was Copilot so alles findet. DSGVO-Verstoß, Presse, Krisenkommunikation.',
        scoreChange: -400,
        reputationChange: -40,
        lesson: 'KI-Rollout ohne Berechtigungskonzept ist ein Datenschutz-Desaster. Copilot zeigt nicht mehr als der User sehen dürfte — aber es ZEIGT es aktiv statt es in Ordnern zu verstecken. Überberechtigungen werden plötzlich sichtbar.',
        triggersEvent: 'DSGVO_INCIDENT',
      },
    ],
    realWorldReference: 'Microsoft Copilot-Rollouts haben 2024 mehrere Datenschutz-Vorfälle verursacht. Unternehmen entdeckten, dass ihre SharePoint-Berechtigungen seit Jahren falsch waren — Copilot machte es sichtbar.',
    bsiReference: 'BSI IT-Grundschutz: APP.6.1 Office-Produkte, CON.2 Datenschutz',
    involvedNpcs: ['CLOUD365-MARTIN', 'CLOUD365-KEVIN'],
    tags: ['copilot', 'ai', 'privacy', 'permissions'],
  },
];
