// Internal NPCs - Scenarios
import { Scenario } from '@kritis/shared';

export const internalScenarios: Scenario[] = [
  {
    id: 'INTERN-SC-001',
    title: 'Budget-Battle: Neue Firewalls',
    category: 'budget_politics',
    difficulty: 3,
    flavorText: 'Die Sophos-Firewalls sind 7 Jahre alt und laufen aus dem Support. Du brauchst neue Hardware - Kostenpunkt: 45.000 Euro. Dein Chef nickt, aber sagt: "Das musst du bei der Hoffmann durchboxen. Viel Glück." Termin bei der Kämmerin ist in einer Stunde.',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Mit technischen Details argumentieren: "End-of-Life bedeutet keine Sicherheits-Updates mehr..."',
        outcome: 'FAIL',
        consequence: 'Die Kämmerin unterbricht nach 30 Sekunden: "Ich verstehe kein Wort. Warum sollte ich 45.000 Euro ausgeben für etwas, das noch funktioniert?" Sie verweist auf den nächsten Haushaltszyklus in 8 Monaten.',
        scoreChange: -50,
        reputationChange: -10,
        lesson: 'Technische Details interessieren Finanzleute nicht. Du musst in ihrer Sprache sprechen: Risiken, Kosten, Compliance.',
      },
      {
        id: 'B',
        text: 'Risiko-basiert argumentieren: "Ohne Updates haften wir bei einem Einbruch. NIS2 verlangt aktuelle Systeme."',
        outcome: 'SUCCESS',
        consequence: 'Die Kämmerin wird aufmerksam bei "Haftung". Sie fragt nach Dokumentation der Compliance-Anforderung. Du zeigst den NIS2-Artikel. Sie seufzt: "Schreiben Sie mir das auf, mit Kostenvergleich zu einem Sicherheitsvorfall. Dann reden wir nochmal."',
        scoreChange: 75,
        reputationChange: 10,
        lesson: 'Kämmerer verstehen Haftungsrisiken. NIS2 und KRITIS-Compliance sind starke Argumente, aber du musst sie belegen können.',
      },
      {
        id: 'C',
        text: 'Kosten eines Ausfalls gegenrechnen: "Ein Tag Ausfall kostet uns 80.000 Euro an Produktivität. Die Firewall kostet 45.000 und hält 7 Jahre."',
        outcome: 'PERFECT',
        consequence: 'Die Kämmerin macht eine Notiz. "Diese Rechnung gefällt mir. Pro Jahr sind das..." Sie rechnet. "...6.400 Euro. Das ist ein Argument." Sie genehmigt unter der Bedingung, dass du drei Angebote einholst und das günstigste nimmst.',
        scoreChange: 150,
        reputationChange: 20,
        lesson: 'ROI in Euro ist die Sprache der Finanzabteilung. Immer Ausfallkosten gegen Investitionskosten rechnen. TCO (Total Cost of Ownership) über die Lebensdauer verteilen.',
      },
      {
        id: 'D',
        text: 'Den Chef vorschicken: "Herr Bergmann, können Sie das nicht mit Frau Hoffmann klären?"',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Der Chef seufzt, geht aber zu Frau Hoffmann. Sie genehmigt, aber merkt sich, dass du "nicht selbst kämpfen kannst". Beim nächsten Mal sagt der Chef: "Das machst DU. Lerneffekt." Dein Standing bei beiden sinkt leicht.',
        scoreChange: 25,
        reputationChange: -5,
        lesson: 'Den Vorgesetzten vorschicken funktioniert kurzfristig, schadet aber langfristig deinem Ruf. Budget-Verhandlungen gehören zu deinem Job.',
      },
    ],
    realWorldReference: 'IT-Budgetgespräche scheitern oft an fehlender Übersetzung zwischen technischer Notwendigkeit und Geschäftssprache.',
    bsiReference: 'BSI IT-Grundschutz: ORP.1 Organisation, ORP.5 Compliance Management',
    involvedNpcs: ['INTERN-KAEMMERER', 'INTERN-CHEF'],
    tags: ['budget', 'firewall', 'compliance', 'kaemmerer'],
  },
  {
    id: 'INTERN-SC-002',
    title: 'Performance Review: Das Jahresgespräch',
    category: 'team_dynamics',
    difficulty: 2,
    flavorText: 'Mitarbeiterjahresgespräch mit dem Chef. Er hat deine Ticket-Statistiken, die Projektergebnisse und das Feedback aus der Fachabteilung vor sich liegen. Die Zahlen sind gut, aber nicht herausragend. Er fragt: "Wie siehst du das vergangene Jahr? Und was sind deine Ziele?"',
    urgency: 'low',
    choices: [
      {
        id: 'A',
        text: 'Ehrlich reflektieren: "Ich habe viel gelernt, aber die AMSE-Situation hätte ich besser managen können."',
        outcome: 'PERFECT',
        consequence: 'Der Chef nickt anerkennend. "Selbstreflexion ist wichtig. Was würdest du anders machen?" Ihr habt ein konstruktives Gespräch. Er schlägt vor, dich zur Fortbildung "Vendor Management" zu schicken. Das Gespräch endet positiv.',
        scoreChange: 100,
        reputationChange: 15,
        lesson: 'Ehrliche Selbstreflexion wird mehr geschätzt als Selbstbeweihräucherung. Zeige, dass du aus Fehlern lernst.',
      },
      {
        id: 'B',
        text: 'Erfolge hervorheben: "Die Firewall-Migration lief reibungslos und unter Budget."',
        outcome: 'SUCCESS',
        consequence: 'Der Chef notiert es. "Stimmt, das war gut." Aber er hakt nach: "Und die drei Wochen VPN-Probleme im Februar? Was war da los?" Du bist in der Defensive. Das Gespräch wird neutral.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Erfolge präsentieren ist wichtig, aber der Chef kennt auch die Probleme. Proaktiv ansprechen ist besser als ausweichen.',
      },
      {
        id: 'C',
        text: 'Auf Beförderung hinarbeiten: "Ich sehe mich als zukünftigen stellvertretenden IT-Leiter."',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Der Chef zieht die Augenbrauen hoch. "Ambitioniert. Was qualifiziert dich dafür?" Du hast keine überzeugende Antwort vorbereitet. Er sagt: "Zeig mir in den nächsten 12 Monaten Leadership, dann reden wir." Du hast dich festgelegt ohne Plan.',
        scoreChange: 25,
        reputationChange: 0,
        lesson: 'Karriereambitionen äußern ist ok, aber nur mit konkretem Plan und Belegen für Qualifikation. Sonst wirkt es wie leere Worte.',
      },
      {
        id: 'D',
        text: 'Mehr Gehalt fordern: "Bei meiner Arbeitsbelastung ist eine Gehaltsanpassung angemessen."',
        outcome: 'FAIL',
        consequence: 'Der Chef wird reserviert. "Das ist ein Mitarbeitergespräch, kein Gehaltsgespräch. Das läuft über HR und Tarifvertrag. Du weißt das." Der Rest des Gesprächs ist angespannt. Er empfiehlt, sich zu informieren wie Gehaltsverhandlungen im öffentlichen Dienst funktionieren.',
        scoreChange: -50,
        reputationChange: -10,
        lesson: 'Gehaltsfragen haben eigene Prozesse (besonders im öffentlichen Dienst/TVöD). Im Jahresgespräch ist das deplatziert und zeigt fehlendes Prozessverständnis.',
      },
    ],
    realWorldReference: 'Jahresgespräche sind entscheidend für die Karriere. Vorbereitung und Selbstreflexion sind Schlüssel.',
    bsiReference: 'BSI IT-Grundschutz: ORP.2 Personal',
    involvedNpcs: ['INTERN-CHEF'],
    tags: ['career', 'performance', 'personal', 'chef'],
  },
  {
    id: 'INTERN-SC-003',
    title: 'GF will Statusbericht für den Aufsichtsrat',
    category: 'compliance',
    difficulty: 3,
    flavorText: 'Dr. Krause ruft an. "Ich brauche bis morgen früh einen Statusbericht IT-Sicherheit für die Aufsichtsratssitzung. Eine Seite maximal. Verständlich für Nicht-Techniker. Und seien Sie ehrlich, aber nicht alarmistisch." Das ist in 18 Stunden.',
    urgency: 'high',
    choices: [
      {
        id: 'A',
        text: 'Eine ehrliche Ampel-Darstellung erstellen: Grün/Gelb/Rot für jeden Bereich',
        outcome: 'PERFECT',
        consequence: 'Du erstellst eine übersichtliche Ampel-Grafik: Firewall (Gelb - Hardware alt), Backup (Grün), Endpoint Security (Grün), KRITIS-Compliance (Gelb - NIS2 in Arbeit). Unter jeder Ampel ein Satz Erklärung. Dr. Krause ist beeindruckt: "Endlich jemand, der verständlich schreibt!" Der Aufsichtsrat genehmigt das Security-Budget.',
        scoreChange: 200,
        reputationChange: 25,
        lesson: 'Ampel-Darstellungen sind Management-Sprache. Grün/Gelb/Rot versteht jeder. Zu viel Grün wirkt unglaubwürdig, zu viel Rot wirkt inkompetent.',
      },
      {
        id: 'B',
        text: 'Nur die Erfolge darstellen, Probleme weglassen',
        outcome: 'FAIL',
        consequence: 'Dein Bericht ist eine Seite "Alles super". Dr. Krause ist skeptisch: "Das glaube ich nicht. Kein IT-Bereich ist problemfrei." Er verlangt einen ehrlichen Bericht. Du musst nacharbeiten und hast das Vertrauen beschädigt.',
        scoreChange: -100,
        reputationChange: -15,
        lesson: 'Ein reiner Erfolgsbericht ist unglaubwürdig. Führungskräfte schätzen ehrliche Risikoeinschätzung mehr als Schönfärberei.',
      },
      {
        id: 'C',
        text: 'Alle technischen Probleme detailliert auflisten',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Dein Bericht ist drei Seiten lang, voller Fachbegriffe. Dr. Krause: "Das kann ich dem Aufsichtsrat nicht zeigen. Die verstehen das nicht und bekommen Panik." Du musst auf eine Seite kürzen und vereinfachen.',
        scoreChange: 25,
        reputationChange: 0,
        lesson: 'Der Aufsichtsrat ist kein technisches Gremium. Management-Berichte müssen auf einer Seite das Wesentliche transportieren.',
      },
      {
        id: 'D',
        text: 'Den Chef bitten, den Bericht zu schreiben',
        outcome: 'SUCCESS',
        consequence: 'Der Chef macht es, ist aber nicht begeistert: "Das hättest du auch gekonnt." Du verpasst eine Chance, dich beim GF zu profilieren. Der Chef macht einen soliden Bericht, aber erwähnt deinen Namen nicht.',
        scoreChange: 50,
        reputationChange: -5,
        lesson: 'Delegieren an den Chef funktioniert, aber jede Gelegenheit, direkt mit dem GF zu interagieren, ist eine Karrierechance.',
      },
    ],
    realWorldReference: 'C-Level-Reporting ist eine Kernkompetenz für IT-Führungskräfte. Die Fähigkeit, Technik für Manager zu übersetzen, unterscheidet gute von durchschnittlichen IT-Leitern.',
    bsiReference: 'BSI IT-Grundschutz: ORP.1 Organisation, ISMS.1 Informationssicherheitsmanagement',
    involvedNpcs: ['INTERN-GF', 'INTERN-CHEF'],
    tags: ['reporting', 'management', 'aufsichtsrat', 'kommunikation'],
  },
  {
    id: 'INTERN-SC-004',
    title: 'Fachabteilung: Die Disposition ist down',
    category: 'troubleshooting',
    difficulty: 3,
    flavorText: 'Montag, 5:47 Uhr. Dein Handy klingelt. Sabine Müller, Dispositionsleiterin: "NICHTS GEHT MEHR! Die Fahrer stehen hier und können keine Routen abrufen! Die Müllabfuhr fährt in 13 Minuten los - OHNE Routen! Machen Sie was!"',
    urgency: 'critical',
    choices: [
      {
        id: 'A',
        text: 'Sofort prüfen: Server-Status, Netzwerk, Datenbank — remote aus dem Bett',
        outcome: 'PERFECT',
        consequence: 'Du loggst dich per VPN ein. Server läuft, Netzwerk ok. Datenbank... Timeout. Du startest den Datenbank-Dienst neu. Nach 4 Minuten läuft alles. Du rufst Sabine an: "Sollte jetzt gehen." Sie bestätigt. Du dokumentierst den Vorfall und schläfst weiter.',
        scoreChange: 200,
        reputationChange: 30,
        lesson: 'Schnelle, systematische Diagnose ist bei Ausfällen alles. Die Fähigkeit, remote aus dem Bett zu arbeiten, ist im IT-Alltag unbezahlbar.',
      },
      {
        id: 'B',
        text: 'Sabine beruhigen und ins Büro fahren',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Du brauchst 25 Minuten ins Büro. Die Fahrer sind mit ausgedruckten Notfall-Routen losgefahren (Sabine hat improvisiert). Du findest das Problem (Datenbank), aber die erste Stunde war chaotisch. Sabine: "Schön dass Sie kommen, aber das hätte schneller gehen müssen."',
        scoreChange: 50,
        reputationChange: 0,
        lesson: 'Bei Notfällen zählt jede Minute. Remote-Zugang und Schnelligkeit sind wichtiger als physische Anwesenheit.',
      },
      {
        id: 'C',
        text: 'Erstmal klären: "Können Sie genauer beschreiben was nicht geht?"',
        outcome: 'FAIL',
        consequence: 'Sabine explodiert: "DIE ROUTEN GEHEN NICHT! Was gibt es da zu beschreiben?!" Während du versuchst, mehr Infos zu bekommen, vergehen 10 Minuten. Die Fahrer fahren ohne Routen los. Der Tag wird chaotisch und teuer.',
        scoreChange: -150,
        reputationChange: -20,
        lesson: 'Bei kritischen Ausfällen ist Handeln wichtiger als vollständige Informationssammlung. "Diagnose während der Reparatur" ist der richtige Ansatz.',
      },
      {
        id: 'D',
        text: 'AMSE anrufen — die haben Rufbereitschaft für genau sowas',
        outcome: 'FAIL',
        consequence: 'AMSEs Rufbereitschaft meldet sich nach 15 Minuten. Marco ist verschlafen: "Firewall ist ok bei euch. Liegt nicht an uns." Die Fahrer sind längst los. Du hättest in 15 Minuten selbst diagnostizieren können.',
        scoreChange: -100,
        reputationChange: -15,
        lesson: 'Externe Dienstleister sind gut für geplante Wartung, aber bei akuten Ausfällen musst du selbst handeln können. Abhängigkeit ist ein Risiko.',
      },
    ],
    realWorldReference: 'Kritische Systeme fallen gerne außerhalb der Arbeitszeit aus. Ein IT-Admin in KRITIS muss jederzeit handlungsfähig sein.',
    bsiReference: 'BSI IT-Grundschutz: DER.2.1 Behandlung von Sicherheitsvorfällen',
    involvedNpcs: ['INTERN-FACHABT'],
    tags: ['notfall', 'disposition', 'datenbank', 'reaktionszeit'],
  },
  {
    id: 'INTERN-SC-005',
    title: 'Bereitschafts-Bingo: Wer nimmt Silvester?',
    category: 'team_dynamics',
    difficulty: 2,
    flavorText: 'Es ist November. Der Bereitschaftsplan für Dezember muss erstellt werden. Michael: "Ich hatte letztes Jahr Weihnachten, dieses Jahr nicht." Lisa: "Ich bin über Silvester auf einer Hochzeit." Jürgen: "Die Kinder haben Ferien, meine Frau arbeitet." Alle schauen dich an.',
    urgency: 'low',
    choices: [
      {
        id: 'A',
        text: 'Selbst Silvester nehmen: "Ich machs, aber dafür nehme ich mir im Januar zwei Ausgleichstage."',
        outcome: 'SUCCESS',
        consequence: 'Das Team ist erleichtert. Du machst Silvester-Bereitschaft. Es passiert zum Glück nichts. Im Januar nimmst du deine Ausgleichstage. Die Stimmung im Team ist gut, aber du fragst dich, ob du zu oft nachgibst.',
        scoreChange: 75,
        reputationChange: 15,
        lesson: 'Manchmal muss jemand den Kürzeren ziehen. Als informelle Führungsperson ist das oft du. Aber: Ausgleich einfordern ist wichtig.',
      },
      {
        id: 'B',
        text: 'Klare Rotation einfordern: "Wir brauchen ein faires System. Wer hatte wann Bereitschaft?"',
        outcome: 'PERFECT',
        consequence: 'Du erstellst eine Übersicht der letzten 24 Monate. Tatsächlich hatte Lisa noch nie ein langes Wochenende, Michael hatte dreimal Silvester-Ausrede. Du schlägst ein Punkte-System vor: Silvester = 3 Punkte, normales Wochenende = 1 Punkt. Das Team grummelt, aber es ist fair.',
        scoreChange: 150,
        reputationChange: 20,
        lesson: 'Transparenz und Fairness lösen Teamkonflikte. Ein dokumentiertes System verhindert Endlosdiskussionen.',
      },
      {
        id: 'C',
        text: 'Den Chef entscheiden lassen: "Herr Bergmann, wir können uns nicht einigen."',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Der Chef verdreht die Augen: "Ihr seid erwachsene Menschen." Er legt fest: Alphabetisch, Michael macht Silvester. Michael ist sauer — auf dich, weil du nicht für ihn gekämpft hast.',
        scoreChange: 25,
        reputationChange: -5,
        lesson: 'Den Chef einzuschalten funktioniert, aber zeigt, dass du Teamkonflikte nicht selbst lösen kannst. Und irgendjemand ist immer sauer.',
      },
      {
        id: 'D',
        text: 'Externe Bereitschaft vorschlagen: "Was kostet Bereitschaft über AMSE über die Feiertage?"',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Du holst ein Angebot ein: 2.500 Euro für Silvester-Bereitschaft. Die Kämmerin lehnt ab: "Das ist unverhältnismäßig." Aber die Diskussion hat Zeit gekostet. Am Ende muss trotzdem einer aus dem Team ran.',
        scoreChange: 0,
        reputationChange: 0,
        lesson: 'Externe Bereitschaft ist teuer und wird selten genehmigt. Ein guter Versuch, aber kein Ersatz für Team-Koordination.',
      },
    ],
    realWorldReference: 'Bereitschaftsplanung ist einer der häufigsten Teamkonflikte in der IT. Transparente Regeln verhindern jährliche Dramen.',
    bsiReference: 'BSI IT-Grundschutz: ORP.2 Personal',
    involvedNpcs: ['INTERN-KOLLEGEN', 'INTERN-CHEF'],
    tags: ['team', 'bereitschaft', 'konflikt', 'planung'],
  },
  {
    id: 'INTERN-SC-006',
    title: 'Büropolitik: Die Fachabteilung will eigene IT',
    category: 'budget_politics',
    difficulty: 4,
    flavorText: 'Gerüchte im Flurfunk: Die Disposition will sich ein eigenes "IT-System" kaufen — ein SaaS-Routing-Tool, das Sabine auf einer Messe gesehen hat. Ohne IT-Beteiligung, direkt über ihr Abteilungsbudget. Der Vertrieb des Anbieters hat schon mit dem GF telefoniert.',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Sabine direkt konfrontieren: "Warum bindet ihr die IT nicht ein?"',
        outcome: 'FAIL',
        consequence: 'Sabine reagiert defensiv: "Weil die IT immer nur sagt warum was nicht geht! Wir brauchen Lösungen!" Der Konflikt eskaliert. Sie geht zum GF, beschwert sich über "IT-Blockade". Du stehst als Verhinderer da.',
        scoreChange: -100,
        reputationChange: -15,
        lesson: 'Direkte Konfrontation ohne Verständnis für die Motivation der anderen Seite führt zur Eskalation.',
      },
      {
        id: 'B',
        text: 'Den GF informieren: "Dr. Krause, die Disposition plant eine IT-Beschaffung ohne IT-Freigabe."',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Der GF versteht das Problem (Datenschutz, Integration, Sicherheit), aber sagt: "Klären Sie das direkt mit Frau Müller. Ich will keine Konflikte zwischen Abteilungen." Du hast ihn informiert, aber musst es trotzdem selbst lösen.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Den GF zu informieren ist richtig, aber die Erwartung, dass er es löst, ist naiv. Du musst es operativ selbst klären.',
      },
      {
        id: 'C',
        text: 'Das Tool selbst evaluieren und eine technische Stellungnahme vorbereiten',
        outcome: 'PERFECT',
        consequence: 'Du recherchierst das Tool: US-Cloud, keine GDPR-Compliance, keine API zum bestehenden ERP, Daten liegen auf AWS us-east-1. Du erstellst eine sachliche Analyse mit Alternativen, die KRITIS-konform sind. Sabine ist genervt, aber das Argument "Datenschutz-Bußgeld bis 4% vom Jahresumsatz" überzeugt den GF. Er stoppt die Beschaffung und lobt deine proaktive Arbeit.',
        scoreChange: 200,
        reputationChange: 25,
        lesson: 'Faktenbasierte Analyse schlägt Büropolitik. Wenn du Risiken aufzeigen kannst (GDPR, KRITIS), bist du kein Blockierer sondern Beschützer.',
      },
      {
        id: 'D',
        text: 'Ignorieren — ist nicht dein Budget, nicht dein Problem',
        outcome: 'CRITICAL_FAIL',
        consequence: 'Sabine kauft das Tool. 3 Monate später: Datenschutzbeauftragter entdeckt, dass Personendaten (Fahrernamen, Adressen) in einer US-Cloud liegen. Meldepflicht an die Aufsichtsbehörde. Der GF fragt: "Warum hat die IT das nicht verhindert?"',
        scoreChange: -250,
        reputationChange: -30,
        lesson: 'Shadow-IT ist immer ein IT-Problem, auch wenn die IT nicht involviert war. Wenn es schiefgeht, wird die IT verantwortlich gemacht.',
        triggersEvent: 'GDPR_INCIDENT',
      },
    ],
    realWorldReference: 'Shadow-IT entsteht wenn Fachabteilungen das Gefühl haben, IT blockiert sie. Der richtige Weg ist: Verstehen, evaluieren, beraten — nicht verbieten.',
    bsiReference: 'BSI IT-Grundschutz: ORP.4 Identitäts- und Berechtigungsmanagement, CON.2 Datenschutz',
    involvedNpcs: ['INTERN-FACHABT', 'INTERN-GF'],
    tags: ['shadow-it', 'datenschutz', 'beschaffung', 'buropolitik'],
  },
  {
    id: 'INTERN-SC-007',
    title: 'Chef verlangt das Unmögliche',
    category: 'team_dynamics',
    difficulty: 4,
    flavorText: 'Der Chef kommt Mittwoch um 16:30: "Der GF will bis Freitag eine komplette Dokumentation aller IT-Assets für den NIS2-Audit. Hardware, Software, Lizenzen, Netzwerk. Vollständig." Das ist normalerweise 2 Wochen Arbeit. Du hast 1,5 Tage.',
    urgency: 'critical',
    choices: [
      {
        id: 'A',
        text: 'Realistisch bleiben: "Das ist in 1,5 Tagen nicht machbar. Was ist die absolute Priorität?"',
        outcome: 'PERFECT',
        consequence: 'Der Chef denkt nach. "OK, was KANNST du bis Freitag liefern?" Ihr einigt euch auf: Kritische Systeme vollständig, Rest als Übersicht. Du arbeitest zwei lange Tage, lieferst ein 80%-Dokument mit klarem Vermerk was noch fehlt. Der GF akzeptiert es: "Besser als erwartet."',
        scoreChange: 150,
        reputationChange: 20,
        lesson: 'Unrealistische Deadlines erfordern Priorisierung, nicht Heroismus. 80% pünktlich ist besser als 100% zu spät.',
      },
      {
        id: 'B',
        text: 'Alles geben: Zwei Nachtschichten durcharbeiten, Team zusammentrommeln',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Du arbeitest durch, Lisa hilft freiwillig, Jürgen nicht (Kinder). Die Dokumentation ist Freitag früh fertig — aber voller Fehler wegen Übermüdung. Der GF findet 3 Inkonsistenzen im Meeting. Außerdem bist du die nächste Woche nicht zu gebrauchen.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'Übermüdete Arbeit produziert Fehler. Kurzfristiger Heroismus schadet langfristig — dir und der Qualität.',
      },
      {
        id: 'C',
        text: 'Ablehnen: "Das geht nicht. Der GF muss den Termin verschieben."',
        outcome: 'FAIL',
        consequence: 'Der Chef reagiert gereizt: "Dann sag DU das dem GF." Du rufst Dr. Krause an, er ist nicht amüsiert: "Ich kann den Audit-Termin nicht verschieben. Finden Sie eine Lösung." Du hast dich unbeliebt gemacht ohne Ergebnis.',
        scoreChange: -100,
        reputationChange: -20,
        lesson: 'Pauschal ablehnen ohne Alternative ist keine Lösung. Immer einen Gegenvorschlag haben.',
      },
      {
        id: 'D',
        text: 'Externe Hilfe holen: AMSE hat Asset-Management-Daten, die nutzen wir',
        outcome: 'SUCCESS',
        consequence: 'Du rufst Marco an: "Ihr habt doch Inventar-Daten von uns. Könnt ihr die exportieren?" Marco liefert eine Excel mit 70% der Hardware-Infos. Du ergänzt die Software selbst. Freitag steht eine solide Dokumentation. Nicht perfekt, aber brauchbar.',
        scoreChange: 100,
        reputationChange: 10,
        lesson: 'Externe Datenquellen nutzen ist clever. Dienstleister haben oft Informationen, die intern fehlen.',
      },
    ],
    realWorldReference: 'Unmögliche Deadlines sind IT-Alltag. Die Kunst ist, realistische Teillieferungen zu verhandeln statt zu scheitern.',
    bsiReference: 'BSI IT-Grundschutz: ORP.1 Organisation, ISMS.1 Informationssicherheitsmanagement',
    involvedNpcs: ['INTERN-CHEF', 'INTERN-GF'],
    tags: ['deadline', 'dokumentation', 'nis2', 'stress'],
  },
  {
    id: 'INTERN-SC-008',
    title: 'IT-Ausgaben unter der Lupe',
    category: 'budget_politics',
    difficulty: 3,
    flavorText: 'Die Kämmerin lädt dich und den Chef zu einem "Kostengespräch" ein. Sie hat eine Excel-Tabelle: "Die IT-Ausgaben sind im letzten Jahr um 23% gestiegen. Ich möchte verstehen, warum. Hier sehe ich: Microsoft-Lizenzen +15%, AMSE-Vertrag +8%, Hardware +42%..."',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Defensiv werden: "IT-Sicherheit kostet eben Geld. Die Alternative ist teurer."',
        outcome: 'FAIL',
        consequence: 'Die Kämmerin wird kühl: "Das ist keine Begründung, das ist eine Ausrede. Ich erwarte konkrete Zahlen, nicht Phrasen." Das Meeting endet frostig. Sie kündigt an, jeden IT-Antrag künftig persönlich zu prüfen.',
        scoreChange: -100,
        reputationChange: -15,
        lesson: 'Finanzleute wollen Fakten, keine Slogans. "Sicherheit kostet Geld" ist kein Argument ohne konkrete Zahlen.',
      },
      {
        id: 'B',
        text: 'Jede Position erklären: Hardware wegen Laptop-Refresh, Lizenzen wegen NIS2-Anforderung, AMSE wegen SLA-Upgrade',
        outcome: 'SUCCESS',
        consequence: 'Du gehst Position für Position durch. Die Kämmerin nickt bei manchen, fragt bei anderen nach. "Der Laptop-Refresh ist nachvollziehbar. Aber der AMSE-Aufschlag — haben Sie verhandelt?" Das Meeting endet neutral, aber du hast nicht glänzend.',
        scoreChange: 75,
        reputationChange: 5,
        lesson: 'Transparenz ist gut, aber proaktive Kostenkontrolle wäre besser gewesen. Die Frage nach Verhandlung zeigt: Du solltest immer eine Antwort darauf haben.',
      },
      {
        id: 'C',
        text: 'Proaktiv mit Kostensenkungsvorschlägen kommen: "Ich habe mir das auch angeschaut. Hier sind Einsparoptionen für nächstes Jahr."',
        outcome: 'PERFECT',
        consequence: 'Du präsentierst: Cloud-Konsolidierung spart 8.000€/Jahr, Microsoft E3 statt E5 spart 3.000€, Dienstleisterwechsel-Evaluierung könnte 15% AMSE-Kosten sparen. Die Kämmerin ist beeindruckt: "Das ist konstruktiv. Lassen Sie uns das vierteljährlich besprechen."',
        scoreChange: 200,
        reputationChange: 25,
        lesson: 'Die beste Verteidigung ist Angriff. Wer selbst Einsparungsvorschläge bringt, hat die Kontrolle über das Gespräch.',
      },
      {
        id: 'D',
        text: 'Den Chef reden lassen — er ist ja IT-Leiter',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Der Chef übernimmt, erklärt solide, aber ohne Begeisterung. Die Kämmerin akzeptiert die Erklärungen. Aber sie merkt an: "Wäre schön, wenn die IT das selbst im Blick hätte." Du hast eine Chance verpasst, Kompetenz zu zeigen.',
        scoreChange: 25,
        reputationChange: -5,
        lesson: 'Budget-Verantwortung ist Leadership. Wer sie delegiert, wird nicht als Führungskraft wahrgenommen.',
      },
    ],
    realWorldReference: 'Regelmäßige Budget-Reviews sind Standard. Vorbereitung mit eigenen Optimierungsvorschlägen zeigt Professionalität.',
    bsiReference: 'BSI IT-Grundschutz: ORP.1 Organisation',
    involvedNpcs: ['INTERN-KAEMMERER', 'INTERN-CHEF'],
    tags: ['budget', 'kosten', 'kaemmerer', 'kontrolle'],
  },
  {
    id: 'INTERN-SC-009',
    title: 'Der GF will auf der Messe präsentieren',
    category: 'compliance',
    difficulty: 2,
    flavorText: 'Dr. Krause: "Ich halte nächste Woche einen Vortrag über Digitalisierung in der Abfallwirtschaft. Ich brauche 3 Folien über unsere IT-Sicherheit. Zeigen Sie, wie modern wir sind." Du weißt: Die Sophos ist alt, das ERP von 2004, und modern ist relativ.',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Ehrlich sein: "Dr. Krause, wir sind nicht so modern wie andere. Das sollten wir nicht übertreiben."',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Der GF ist enttäuscht: "Also können wir nicht mal positiv über unsere IT reden?" Du wirkst destruktiv. Er fragt den Chef, ob "der Neue immer so pessimistisch" ist.',
        scoreChange: 25,
        reputationChange: -10,
        lesson: 'Ehrlichkeit ist gut, aber "wir sind schlecht" ist keine hilfreiche Aussage. Immer einen positiven Spin finden.',
      },
      {
        id: 'B',
        text: 'Marketing-Folien erstellen: "KRITIS-Compliance, 24/7-Monitoring, modernste Firewall-Technologie"',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Der Vortrag läuft gut. Aber ein Kollege aus einem anderen Entsorgungsbetrieb fragt nach: "Welche Firewall nutzt ihr?" Der GF leitet die Frage an dich weiter. "Sophos XG... Baujahr 2017." Peinliche Stille.',
        scoreChange: 50,
        reputationChange: 0,
        lesson: 'Marketing-Aussagen müssen nachfragefest sein. Übertreibungen fallen auf.',
      },
      {
        id: 'C',
        text: 'Positiv aber wahrheitsgemäß: "Wir zeigen: KRITIS-Sicherheitskonzept, BSI-Grundschutz in Arbeit, konkrete Roadmap"',
        outcome: 'PERFECT',
        consequence: 'Du erstellst Folien: Ist-Stand, laufende Projekte, Zielbild 2025. Ehrlich, aber professionell. Der GF ist zufrieden: "Das zeigt, dass wir wissen wo wir stehen und wohin wir wollen." Der Vortrag kommt gut an.',
        scoreChange: 150,
        reputationChange: 20,
        lesson: 'Roadmaps und Pläne sind genauso vorzeigbar wie fertige Projekte. "Wir arbeiten dran" ist ein valides Statement.',
      },
      {
        id: 'D',
        text: 'Ablehnen: "Ich bin nicht fürs Marketing zuständig."',
        outcome: 'FAIL',
        consequence: 'Der GF ist irritiert: "Ich bitte Sie um 3 Folien, nicht um eine Dissertation." Er fragt den Chef, der es dann macht. Du hast dich als unflexibel geoutet.',
        scoreChange: -75,
        reputationChange: -15,
        lesson: 'Kleine Aufgaben vom GF abzulehnen ist politisch unklug, egal ob es "dein Job" ist oder nicht.',
      },
    ],
    realWorldReference: 'Management-Kommunikation ist IT-Aufgabe. Die Fähigkeit, Technik positiv aber ehrlich darzustellen, ist Karriere-relevant.',
    bsiReference: 'BSI IT-Grundschutz: ISMS.1 Informationssicherheitsmanagement',
    involvedNpcs: ['INTERN-GF'],
    tags: ['kommunikation', 'marketing', 'vortrag', 'politik'],
  },
  {
    id: 'INTERN-SC-010',
    title: 'Kollegen-Krach: Legacy vs. Cloud',
    category: 'team_dynamics',
    difficulty: 3,
    flavorText: 'Team-Meeting. Lisa präsentiert: "Wir sollten das ERP in die Cloud migrieren. Azure hat alles, was wir brauchen." Michael explodiert: "Das ERP läuft seit 20 Jahren stabil! Du willst alles kaputtmachen für deinen Cloud-Hype!" Die Stimmung kippt.',
    urgency: 'low',
    choices: [
      {
        id: 'A',
        text: 'Lisa unterstützen: "Die Cloud ist die Zukunft. Wir müssen modernisieren."',
        outcome: 'FAIL',
        consequence: 'Michael fühlt sich nicht ernst genommen: "Ihr jungen Leute habt keine Ahnung von stabilen Systemen!" Er droht mit Krankmeldung. Das Team ist gespalten. Jürgen seufzt und schaut auf die Uhr.',
        scoreChange: -75,
        reputationChange: -10,
        lesson: 'Partei ergreifen in einem Teamkonflikt spaltet das Team weiter. Dein Job ist Moderation, nicht Positionierung.',
      },
      {
        id: 'B',
        text: 'Michael unterstützen: "Das ERP läuft. Never change a running system."',
        outcome: 'FAIL',
        consequence: 'Lisa ist frustriert: "Dann bleiben wir halt ewig im Jahr 2004!" Sie droht mit Wechsel zu einem moderneren Arbeitgeber. Talentbindung wird ein Problem.',
        scoreChange: -75,
        reputationChange: -10,
        lesson: 'Die andere Seite zu nehmen hat den gleichen Effekt: Spaltung. Und du verlierst junge Talente.',
      },
      {
        id: 'C',
        text: 'Moderieren: "Beide haben Punkte. Lisa, was ist der Business Case? Michael, welche Risiken siehst du konkret?"',
        outcome: 'PERFECT',
        consequence: 'Du strukturierst die Diskussion. Lisa soll einen Business Case schreiben, Michael eine Risikoanalyse. Ihr vereinbart, beide im nächsten Meeting zu besprechen. Die Emotionen sinken, die Fakten kommen. Michael und Lisa sprechen nach dem Meeting miteinander.',
        scoreChange: 150,
        reputationChange: 20,
        lesson: 'Technik-Diskussionen eskalieren, wenn es um Identität geht (alt vs. neu). Moderation über Fakten entpersonalisiert den Konflikt.',
      },
      {
        id: 'D',
        text: 'Thema vertagen: "Das besprechen wir ein andermal. Nächster Punkt."',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Das Meeting geht weiter, aber der Konflikt schwelt. In den nächsten Wochen ignorieren Lisa und Michael sich. Die Teamdynamik leidet.',
        scoreChange: 0,
        reputationChange: -5,
        lesson: 'Konflikte vertagen löst sie nicht. Aufgeschoben ist nicht aufgehoben.',
      },
    ],
    realWorldReference: 'Der Generationenkonflikt Legacy vs. Cloud ist in vielen IT-Teams real. Moderation statt Positionierung ist der Schlüssel.',
    bsiReference: 'BSI IT-Grundschutz: ORP.2 Personal',
    involvedNpcs: ['INTERN-KOLLEGEN'],
    tags: ['team', 'konflikt', 'cloud', 'legacy', 'moderation'],
  },
];
