// Deutsche Telekom Business - Scenarios
import { Scenario } from '@kritis/shared';

export const telekomScenarios: Scenario[] = [
  {
    id: 'TELEKOM-SC-001',
    title: 'Die Leitung ist weg — aber nur manchmal',
    category: 'troubleshooting',
    difficulty: 3,
    flavorText: 'Seit 3 Tagen berichten Kollegen von sporadischen Internet-Ausfällen. Manchmal 5 Minuten, manchmal 30 Sekunden. Du rufst die Telekom an. Thomas Kellermann: "Ich sehe hier keine Störung. Haben Sie den Router schon neugestartet?" Der Router wurde schon 4x neugestartet.',
    urgency: 'high',
    choices: [
      {
        id: 'A',
        text: 'Eigenes Monitoring aufsetzen und Ausfälle mit Timestamps dokumentieren',
        outcome: 'PERFECT',
        consequence: 'Du installierst ein einfaches Monitoring (Ping zu 3 externen IPs alle 30 Sekunden). Nach 2 Tagen hast du: 47 Micro-Outages, immer zwischen 10-14 Uhr, nie länger als 90 Sekunden. Du schickst Thomas die Logs. Er: "Ah, das ist ein Pattern. Das sieht nach einem überlasteten Verteiler aus. Ich lass das prüfen." Techniker findet einen defekten Verstärker am Outdoor-DSLAM.',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'Provider können nur Probleme lösen die sie sehen. Dein eigenes Monitoring liefert Beweise. "Manchmal geht das Internet nicht" ist keine brauchbare Störungsmeldung — Timestamps und Patterns schon.',
      },
      {
        id: 'B',
        text: 'Auf Thomas bestehen: "Schicken Sie einen Techniker"',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Thomas: "Techniker-Termin ist Donnerstag, 8-17 Uhr." Donnerstag: Techniker kommt um 15:47 Uhr. Misst einmal die Leitung: "Alles in Ordnung, 195 Mbit, keine Fehler." Natürlich — während der Messung war gerade kein Ausfall. Problem bleibt bestehen.',
        scoreChange: 0,
        reputationChange: 0,
        lesson: 'Ein einmaliger Techniker-Besuch findet intermittierende Probleme selten. Nur Langzeit-Monitoring oder Provider-seitige Logs über Tage können solche Muster erkennen.',
      },
      {
        id: 'C',
        text: 'Den Router durch eigenes Gerät ersetzen um Hardware-Fehler auszuschließen',
        outcome: 'SUCCESS',
        consequence: 'Du ersetzt die Telekom-Fritzbox durch deine eigene pfSense. Gleiches Problem. Damit ist der Router ausgeschlossen. Du gehst zurück zur Telekom mit klarer Aussage: "Eigener Router, gleiches Problem. Das Problem ist vor dem Router." Thomas eskaliert jetzt ernster.',
        scoreChange: 100,
        reputationChange: 10,
        lesson: 'Eigene Hardware zu verwenden hilft beim Ausschlussverfahren. Wenn das Problem auch mit eigener Hardware auftritt, ist der Provider-Router nicht schuld — und das nimmt dem Provider das Standard-Argument.',
      },
    ],
    realWorldReference: 'Intermittierende Verbindungsprobleme sind die schwierigsten zu diagnostizieren. Automatisiertes Monitoring ist der einzige zuverlässige Weg, sie zu dokumentieren.',
    bsiReference: 'BSI IT-Grundschutz: NET.1.2 Netzmanagement',
    involvedNpcs: ['TELEKOM-THOMAS'],
    tags: ['wan', 'troubleshooting', 'monitoring', 'documentation'],
  },
  {
    id: 'TELEKOM-SC-002',
    title: 'Wartungsankündigung: "Geplante Arbeiten im Backbone"',
    category: 'crisis_management',
    difficulty: 2,
    flavorText: 'Mittwoch, 14:00 Uhr. Mail von noreply@telekom.de: "Am kommenden Samstag, 02:00-06:00 Uhr, führen wir Wartungsarbeiten durch. Kurzzeitige Verbindungsunterbrechungen möglich." Problem: Eure Müllabfuhr startet samstags um 05:00 Uhr und braucht die Dispo-Verbindung.',
    urgency: 'medium',
    choices: [
      {
        id: 'A',
        text: 'Thomas anrufen und um Verschiebung oder Zeitfenster-Zusage bitten',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Thomas: "Backbone-Wartungen kann ich nicht verschieben, das ist deutschlandweit koordiniert. Aber ich kann prüfen ob euer Segment betroffen ist." Nach 2 Stunden: "Ihr Segment wird voraussichtlich gegen 03:30 gewartet, danach sollte alles laufen. Aber keine Garantie." Du planst einen Workaround mit mobiler Datenverbindung als Backup.',
        scoreChange: 75,
        reputationChange: 5,
        lesson: 'Backbone-Wartungen sind nicht verhandelbar, aber Provider können oft Details zu Timing und betroffenen Segmenten geben. Das hilft bei der Planung von Workarounds.',
      },
      {
        id: 'B',
        text: 'Redundante Verbindung über Mobilfunk aktivieren und automatisches Failover einrichten',
        outcome: 'PERFECT',
        consequence: 'Du aktivierst eure LTE-Backup-Verbindung mit automatischem Failover in der pfSense. Am Samstag: Hauptverbindung fällt um 03:12 aus, Failover auf LTE in 8 Sekunden. Dispo-System läuft unterbrechungsfrei. Hauptleitung um 04:47 wieder da. Automatisches Failback. Niemand hat etwas gemerkt.',
        scoreChange: 200,
        reputationChange: 15,
        lesson: 'Redundanz ist die Antwort auf geplante und ungeplante Ausfälle. Automatisches Failover bedeutet: Du musst nicht um 03:00 Uhr wach sein um umzuschalten. KRITIS-Infrastruktur braucht immer einen Plan B.',
        followupEvent: 'REDUNDANCY_SUCCESS',
      },
      {
        id: 'C',
        text: 'Samstags-Dispo auf Montag verschieben — ein Tag ohne Müllabfuhr ist akzeptabel',
        outcome: 'FAIL',
        consequence: 'Die Fachabteilung ist entsetzt: "Ein Samstag ohne Abfuhr? Im Sommer? Bei 30 Grad?" Der GF ruft an: "Finden Sie eine andere Lösung." Du organisierst hastig Offline-Papierlisten für die Fahrer. Chaos am Samstag, 3 Touren fahren falsche Routen.',
        scoreChange: -150,
        reputationChange: -20,
        lesson: 'IT-Wartungsfenster auf Geschäftsprozesse abzuwälzen ist keine Lösung. Die IT muss Continuity gewährleisten, nicht die Fachabteilung mit Workarounds belasten.',
      },
    ],
    realWorldReference: 'Provider-Wartungen finden oft nachts statt, aber "nachts" kann für 24/7-Betriebe wie Entsorgung kritisch sein. Redundante Anbindung ist bei KRITIS Standard.',
    bsiReference: 'BSI IT-Grundschutz: DER.4 Notfallmanagement',
    involvedNpcs: ['TELEKOM-THOMAS'],
    tags: ['maintenance', 'redundancy', 'planning', 'kritis'],
  },
  {
    id: 'TELEKOM-SC-003',
    title: 'Die SLA-Beschwerde nach dem Jahresausfall',
    category: 'vendor_management',
    difficulty: 3,
    flavorText: 'Jahresgespräch mit der Telekom. Sabine bringt bunte PowerPoints mit "99.7% Verfügbarkeit — SLA erfüllt!" Deine eigenen Zahlen: 14 Störungen, 27 Stunden Ausfall, rechnerisch 99.69%. Knapp über dem SLA-Minimum von 99.5%. Aber: 8 Stunden davon waren an einem Dienstag um 10 Uhr morgens.',
    urgency: 'low',
    choices: [
      {
        id: 'A',
        text: 'Akzeptieren — SLA ist formal erfüllt, auch wenn es sich anders anfühlt',
        outcome: 'FAIL',
        consequence: 'Sabine lächelt: "Dann sind wir ja einig. Zur Vertragsverlängerung — wir bieten 5% Rabatt bei 3-Jahres-Laufzeit." Du unterschreibst. Nächstes Jahr: gleiche Probleme, aber jetzt mit 3-Jahres-Vertrag ohne Ausstiegsoption.',
        scoreChange: -100,
        reputationChange: -10,
        lesson: 'SLA-Erfüllung auf dem Papier bedeutet nicht, dass der Service gut ist. Die Verteilung der Ausfälle ist genauso wichtig wie die Gesamtmenge. 8 Stunden Ausfall am Dienstag 10 Uhr ist schlimmer als 8 Stunden nachts.',
      },
      {
        id: 'B',
        text: 'Mit eigener Ausfallstatistik argumentieren: "SLA sagt nichts über Timing"',
        outcome: 'SUCCESS',
        consequence: 'Du zeigst deine Dokumentation: "99.7% klingt gut, aber 8 Stunden am Dienstag Vormittag haben uns €12.000 Produktivität gekostet. Ihre Nachtausfälle tun nicht weh, aber Business-Hours-Ausfälle schon." Sabine wird unsicher: "Was schlagen Sie vor?" Du forderst: SLA-Differenzierung nach Geschäftszeiten.',
        scoreChange: 150,
        reputationChange: 15,
        lesson: 'Eigene Dokumentation ist Macht in Verhandlungen. SLAs mit Differenzierung nach Geschäftszeiten (99.9% 8-18 Uhr, 99% nachts) sind für KRITIS sinnvoller als Pauschal-SLAs.',
      },
      {
        id: 'C',
        text: 'Anbieter-Wechsel androhen: "Wir evaluieren gerade Vodafone Business"',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Sabine wird blass: "Lassen Sie uns über Verbesserungen sprechen!" Du bekommst einen Technical Account Manager zugewiesen und ein Premium-Support-Paket kostenlos für 1 Jahr. Aber: Vodafone evaluieren wäre tatsächlich 6 Monate Arbeit. Deine Drohung war ein Bluff.',
        scoreChange: 75,
        reputationChange: 10,
        lesson: 'Anbieterwechsel anzudrohen wirkt — aber nur wenn man es im Notfall auch durchziehen könnte. Sonst ist man beim nächsten Mal der Kunde der nur blufft. Alternative Angebote einzuholen ist auch ohne Wechselabsicht sinnvoll für Verhandlungen.',
      },
    ],
    realWorldReference: 'SLA-Gespräche sind oft Formalität. Provider zeigen bunte Zahlen, Kunden nicken. Eigene Dokumentation und konkrete Forderungen ändern die Dynamik.',
    bsiReference: 'BSI IT-Grundschutz: OPS.2.1 Outsourcing',
    involvedNpcs: ['TELEKOM-SABINE'],
    tags: ['sla', 'negotiation', 'contract', 'documentation'],
  },
  {
    id: 'TELEKOM-SC-004',
    title: 'Router kaputt — aber welcher Ersatz?',
    category: 'troubleshooting',
    difficulty: 2,
    flavorText: 'Freitagmorgen, 7:30 Uhr. Der Telekom-Router ist tot. Keine LEDs, keine Reaktion. Du rufst die Störungshotline an. Nach 25 Minuten: "Der Techniker bringt einen Ersatz-Router. Termin: Montag." Drei Tage ohne Internet im Hauptgebäude.',
    urgency: 'critical',
    choices: [
      {
        id: 'A',
        text: 'Eskalieren: "Wir sind KRITIS-Betreiber, wir brauchen heute noch einen Ersatz!"',
        outcome: 'SUCCESS',
        consequence: 'Nach 3 Eskalationsstufen und einem Anruf bei Sabine (Key Account) wird ein Techniker aus Düsseldorf zu euch geschickt. Ankunft: 16:30 Uhr. Neuer Router läuft um 18:00 Uhr. Freitag gerettet — mit viel Aufwand.',
        scoreChange: 100,
        reputationChange: 10,
        lesson: 'KRITIS-Status hilft bei Eskalationen, aber nur wenn der Provider ihn kennt und der Vertrag das abbildet. Ohne Key-Account-Beziehung wärst du Montag dran gewesen.',
      },
      {
        id: 'B',
        text: 'Eigenen Ersatz-Router konfigurieren und Telekom-Zugangsdaten eingeben',
        outcome: 'PERFECT',
        consequence: 'Du holst eure Ersatz-pfSense aus dem Lager, gibst die PPPoE-Zugangsdaten ein (die du vorausschauend dokumentiert hattest). Internet läuft um 8:15 Uhr wieder. Du rufst die Telekom erst dann an: "Router defekt, ich brauche Ersatz, aber Internet läuft erstmal über eigene Hardware."',
        scoreChange: 250,
        reputationChange: 25,
        lesson: 'Ersatz-Hardware vorhalten und Zugangsdaten dokumentieren macht dich unabhängig vom Provider-Tempo. PPPoE-Credentials sollten griffbereit sein — nicht erst beim Ausfall suchen.',
      },
      {
        id: 'C',
        text: 'LTE-Hotspot aufbauen und das Wochenende überbrücken',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Du verteilst 3 Firmen-Handys als Hotspots. Notbetrieb läuft, aber: 20 Mbit geteilt durch 40 Mitarbeiter ist sehr langsam. Cloud-Anwendungen laggen, VPN ins Rathaus funktioniert kaum. Montag freuen sich alle auf den neuen Router.',
        scoreChange: 50,
        reputationChange: 5,
        lesson: 'LTE-Backup für Notfälle ist besser als nichts, aber kein vollwertiger Ersatz für eine Geschäftsleitung. Kapazität und Latenz sind oft nicht ausreichend für normale Produktivität.',
      },
    ],
    realWorldReference: 'Hardware-Ausfälle passieren. Provider-SLA sagt "Next Business Day" — das kann bei Freitags-Ausfällen 3 Tage bedeuten. Eigene Ersatzhardware eliminiert dieses Risiko.',
    bsiReference: 'BSI IT-Grundschutz: DER.4 Notfallmanagement',
    involvedNpcs: ['TELEKOM-THOMAS', 'TELEKOM-SABINE'],
    tags: ['hardware', 'emergency', 'redundancy', 'planning'],
  },
  {
    id: 'TELEKOM-SC-005',
    title: 'Der Verteilerkasten im Hochwasser',
    category: 'crisis_management',
    difficulty: 4,
    flavorText: 'Starkregen-Ereignis in der Region. Euer Internet ist weg, das Telefon auch. Thomas meldet sich per Handy: "Der Outdoor-Verteiler am Kreisverkehr steht unter Wasser. Betrifft 340 Anschlüsse im Gewerbegebiet. Reparatur frühestens übermorgen — wir müssen auf trockene Straßen warten."',
    urgency: 'critical',
    choices: [
      {
        id: 'A',
        text: 'Notfall-Plan aktivieren: Satellitenverbindung + LTE-Fallback',
        outcome: 'PERFECT',
        consequence: 'Ihr habt für genau diesen Fall eine Starlink-Antenne im Keller. 30 Minuten später: 100 Mbit über Satellit. Die Dispo läuft, die Leitstelle ist erreichbar, die Müllabfuhr fährt. Drei Konkurrenten im Gewerbegebiet stehen komplett still.',
        scoreChange: 300,
        reputationChange: 30,
        lesson: 'Disaster Recovery heißt: Der Plan existiert BEVOR das Disaster passiert. Satellitenverbindung als letzter Fallback bei regionalen Ausfällen ist bei KRITIS Gold wert. Das Starlink-Abo kostet 100€/Monat — der Ausfall kostet 100€/Stunde.',
      },
      {
        id: 'B',
        text: 'Zum Verteiler fahren und Lage selbst einschätzen',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Du fährst hin: Der Kasten steht tatsächlich 30cm im Wasser. Aber: 50m weiter ist ein zweiter Verteiler, trocken. Du rufst Thomas an: "Kann man unser Kabel auf den trockenen Verteiler umpatchen?" Thomas: "Technisch ja, aber das dauert genau so lang wie die Reparatur." Immerhin weißt du jetzt, dass es eine Alternative gäbe.',
        scoreChange: 50,
        reputationChange: 10,
        lesson: 'Vor-Ort-Kenntnis der Infrastruktur hilft. Zu wissen wo der Verteiler ist und welche Alternativen existieren, macht dich zu einem besseren Gesprächspartner für den Provider.',
      },
      {
        id: 'C',
        text: 'Warten und den Notbetrieb mit Handys organisieren',
        outcome: 'FAIL',
        consequence: '48 Stunden Notbetrieb mit Handys. Die Leitstelle kann die Fahrzeuge nicht tracken. Zwei Sammelfahrzeuge fahren dieselbe Tour doppelt. Eine Beschwerde-Welle rollt an. Der GF fragt: "Haben wir keinen Plan für sowas?"',
        scoreChange: -200,
        reputationChange: -20,
        lesson: 'Naturereignisse sind vorhersehbar (nicht wann, aber dass). KRITIS-Betreiber müssen Pläne für regionale Infrastrukturausfälle haben. Warten ist keine Strategie.',
      },
    ],
    realWorldReference: 'Das Ahrtal-Hochwasser 2021 hat gezeigt: Regionale Infrastruktur kann komplett ausfallen. Satelliten-Backup (Starlink, Konnect) wird seitdem bei KRITIS-Betreibern häufiger eingeplant.',
    bsiReference: 'BSI IT-Grundschutz: DER.4 Notfallmanagement, INF.1 Allgemeines Gebäude',
    involvedNpcs: ['TELEKOM-THOMAS'],
    tags: ['disaster', 'redundancy', 'satellite', 'planning'],
  },
  {
    id: 'TELEKOM-SC-006',
    title: 'Der mysteriöse Bandbreiten-Einbruch',
    category: 'troubleshooting',
    difficulty: 3,
    flavorText: 'Seit einer Woche beschweren sich alle: "Das Internet ist so langsam!" Dein Monitoring zeigt: Statt 200 Mbit nur noch 47 Mbit. Du rufst Thomas an. "Bei uns sieht alles normal aus. Haben Sie vielleicht intern einen Download-Server laufen der alles blockiert?"',
    urgency: 'high',
    choices: [
      {
        id: 'A',
        text: 'Interne Analyse: Wer verbraucht die Bandbreite?',
        outcome: 'PARTIAL_SUCCESS',
        consequence: 'Du analysierst: Kein interner Verursacher. Alle PCs zusammen machen 12 Mbit. Der Rest fehlt einfach. Du gehst zurück zur Telekom: "Intern ist niemand. Die 47 Mbit sind schon auf der Leitung, nicht unser Verbrauch." Thomas muss jetzt auf seiner Seite suchen.',
        scoreChange: 75,
        reputationChange: 5,
        lesson: 'Intern auszuschließen ist wichtig, bevor man den Provider beschuldigt. Aber: Nicht zu lange suchen — wenn intern nichts ist, ist es extern.',
      },
      {
        id: 'B',
        text: 'Speedtest direkt am Router durchführen und Provider-seitige Messung fordern',
        outcome: 'PERFECT',
        consequence: 'Du machst einen Speedtest direkt am Router (per Kabel, ohne WLAN): 47 Mbit. Dann forderst du von Thomas eine Messung am DSLAM: "Die Synchronisation zeigt nur 52 Mbit — ihre Leitung ist auf 200 Mbit gebucht." Es stellt sich heraus: Nach einer Wartung wurde euer Profil versehentlich auf "Business 50" gesetzt statt "Business 200".',
        scoreChange: 200,
        reputationChange: 20,
        lesson: 'Provider-seitige Fehler passieren oft nach Wartungen oder Umkonfigurationen. Die Kombination aus eigener Messung und Provider-Messung findet solche Probleme schnell. Fordern Sie immer DSLAM-Sync-Werte, nicht nur "Leitung ist ok".',
      },
      {
        id: 'C',
        text: 'Annehmen dass das temporär ist und abwarten',
        outcome: 'FAIL',
        consequence: '3 Wochen später: Immer noch 47 Mbit. Die Cloud-Backups laufen nicht mehr durch, weil sie zu lange dauern. Thomas: "Oh, ich seh hier das Profil ist falsch... das hätten Sie früher sagen müssen!" Du: "Hab ich vor 3 Wochen..." Thomas: "Das Ticket wurde geschlossen weil Sie nicht geantwortet haben." (Hast du, per Mail, aber das zählt nicht im Telekom-System.)',
        scoreChange: -150,
        reputationChange: -10,
        lesson: 'Telekommunikationsprobleme "verschwinden" selten von selbst. Jeder Tag Warten ist ein Tag verlorener Produktivität. Frühzeitig und hartnäckig nachfragen.',
      },
    ],
    realWorldReference: 'Falsche Provisioning-Profile nach Wartungen sind ein häufiger Provider-Fehler. Kunden zahlen für 200 Mbit, bekommen 50 — oft monatelang unbemerkt, wenn kein eigenes Monitoring läuft.',
    bsiReference: 'BSI IT-Grundschutz: NET.1.2 Netzmanagement',
    involvedNpcs: ['TELEKOM-THOMAS'],
    tags: ['bandwidth', 'monitoring', 'provisioning', 'troubleshooting'],
  },
];
